### ISSUE TITLE
nbsphinx not using numba-jitted function

### ISSUE THREAD

**Issue by tritemio** [spatialaudio/nbsphinx#116]
Hi,

I have a small package with a function optimized with the `numba.jit` decorator. An example notebook showcases the use of the function. When I run the notebook directly the jitted function is very fast (~1s). When I try to build the documentation, however, sphinx throws a timeout error because that function execution takes too long (without numba-jitting the function is > 100x slower). I know I can use `nbsphinx_timeout` in conf.py to increase the timeout, but I still need to wait ~10min for building docs that would otherwise take seconds.

Any idea of why the numba-optimized function is not loaded when run through sphinx?

**Comment by mgeier** [comment]
Sorry, I have no idea.

The first thing you should try is to run it with `nbconvert` using the `--execute` flag, because this is essentially what `nbsphinx` does. Probably this is something you should report to the nbconvert project.

Either way, you should try to reduce your example notebook to the minimum code (with as few dependencies as possible) that shows the problem. Then you should upload this somewhere (e.g. as a Gist) for others to try.

**Comment by tritemio** [comment]
@mgeier, yes nbconvert has the same issue. I'll report it to them, thanks.
