### ISSUE TITLE
Can we have custom javascript components that we added in notebook available in HTML generated by Sphinx?

### ISSUE THREAD

**Issue by SpikingNeurons** [spatialaudio/nbsphinx#140]
Can we have custom javascript components that we added in notebook available in HTML generated by Sphinx?

Sorry I still did not try out the code yet. Just wanted to know the answer for above question.

I am tired of finding solutions :( .... today night I will give a try to nbsphinx.

All I want is that the notebooks with all Disqus, javascript and widgets are retained in generated HTML and the nice things like navigation offered by Sphinx...

I hope it is possible, if not point me too some good resources, So I can bang my head over there ... :P

**Comment by mgeier** [comment]
> Sorry I still did not try out the code yet.

That's not how this works. You'll have to try out yourself whether whatever you want to achieve works or not.

>  Just wanted to know the answer for above question.

The answer is: probably.

If something doesn't work as you would like it to work, feel free to report it here.
And please provide an example notebook, otherwise I don't really know what you are trying to do.

You can also use the "search" function here on Github to check if someone else has already reported similar problems.

**Comment by SpikingNeurons** [comment]
Thanks, I looked at the nbconvert, looks like by custom modifications only I can manage to integrate Javascript components.
