### ISSUE TITLE
Version 0.2.15 breaks build

### ISSUE THREAD

**Issue by abchenson** [spatialaudio/nbsphinx#142]
Hi -- just tried upgrading to 0.2.15, and a previously working sphinx build now breaks with the following error:

```Exception occurred:```
 ``` File "/home/joe-h/miniconda3/envs/bmll-docs/lib/python3.6/site-packages/nbsphinx.py", line 1099, in apply```
   ``` title = sig['ids'][0]```
```IndexError: list index out of range```

log
[sphinx-err-f73pf565.log](https://github.com/spatialaudio/nbsphinx/files/1446355/sphinx-err-f73pf565.log)
 file attached

**Comment by tdaff** [comment]
I see the same thing when building docs for https://github.com/libAtoms/QUIP


[sphinx-err-obiNaL.log](https://github.com/spatialaudio/nbsphinx/files/1446410/sphinx-err-obiNaL.log)

**Comment by cathalmccabe** [comment]
I see the same on readthedocs for https://github.com/xilinx/PYNQ

https://readthedocs.org/projects/pynq-testing/builds/6230240/

**Comment by mgeier** [comment]
Sorry for the breakage!
This was added in #135, it looks like sometimes the list of IDs in a signature can be empty ...?

@clenk Do you know a way how to fix this?

**Comment by clenk** [comment]
Looks like it's caused by duplicate domain objects. For example, the PYNQ error seems to be caused by For example, see http://pynq.readthedocs.io/en/v2.0/pynq_package/pynq.gpio.html - There are 2 versions of `index`, `path`, and `direction` but only the first of each is linkable.

For QUIP, it seems to be caused by multiple `diff_min_image` here: http://libatoms.github.io/QUIP/atoms.html#quippy.atoms.Atoms.diff_min_image

This isn't a problem with these libraries but a bug in `nbsphinx`, so I've made a PR to catch this error.

**Comment by mgeier** [comment]
Thanks @clenk for the quick fix!
I'll make a new release tomorrow if nothing else comes up.

**Comment by tdaff** [comment]
Works for me, thanks!

**Comment by abchenson** [comment]
thanks -- no more failing builds with 0.2.16
