### ISSUE TITLE
bokeh plot in notebook causes TypeError

### ISSUE THREAD

**Issue by thvitt** [spatialaudio/nbsphinx#148]
When trying to run a notebook that contains a simple bokeh plot through nbsphinx, sphinx reproducibly fails:

```
Running Sphinx v1.6.5
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
reading sources... [ 50%] bokeh
Notebook error:
TypeError in bokeh.ipynb:
Object of type 'Undefined' is not JSON serializable
```

[Here is a simple example project.](https://gist.github.com/thvitt/2dd8019ed213ac21dfc67eb223d4f206) I've tried to have a look at a [stack trace](https://github.com/DARIAH-DE/Topics/issues/14#issuecomment-337629499) but don't really understand what's going on …

nbsphinx==0.2.17
bokeh==0.12.11

**Comment by mgeier** [comment]
OK, I think I know what's the problem, but I'm not sure about the solution ...

First of all, it turns out that the full name of `'Undefined'` is `jinja2.runtime.Undefined`.

And it seems to be caused by something like this in the notebook JSON:

    "application/vnd.bokehjs_exec.v0+json": "..."

It looks like `nbconvert` ignores that, but `nbsphinx` doesn't.

`nbsphinx` looks for a string like `'application*+json'`. If I change this to `'application/vnd.jupyter*+json'`, the error goes away.

I'm not sure though if that's the right thing to do.
Pinging @SylvainCorlay because he wrote this code.

**Comment by SylvainCorlay** [comment]
Adding `/vnd.jupyter` as suggested should do the trick and be fine with jupyter widgets.  I am not in a position to test right now though.

**Comment by mgeier** [comment]
Thanks for the quick response @SylvainCorlay!

I've created #149 to fix this issue.

I guess if something other than "vnd.jupyter" needs this feature, we'll have to whitelist them whenever need arises.

@thvitt  Can you please check if that works for you?

**Comment by thvitt** [comment]
Works wonderful with both the test project and the notebooks in which we need this. @mgeier, @SylvainCorlay, many thanks for the fast fix!
