### ISSUE TITLE
add .ipynb files to toctree using wildcard

### ISSUE THREAD

**Issue by ltalirz** [spatialaudio/nbsphinx#151]
Would it be possible to allow for something like the following?
```
.. toctree::
   :titlesonly:
   :glob:

   *.ipynb
```
My usecase is that people are adding jupyter notebooks to a folder and I am using nbsphinx to automatically create html versions of each of them for the documentation.

Currently, I believe the above code actually tells sphinx to search for files `*.ipynb.rst` and thus results in `WARNING: toctree glob pattern '*.ipynb' didn't match any documents`

For the moment, I simply add all `.ipynb` files by hand, but being able to use a wildcard would make life simpler.

P.S. When I started looking a bit through the code I came across this:
https://github.com/spatialaudio/nbsphinx/blob/b0542b404383e08c52574ea72ec318a941b4991d/src/nbsphinx.py#L1333-L1343
Not sure whether this is related, but perhaps it is it time to do the replacement now?

**Comment by mgeier** [comment]
It should work without the `.ipynb` suffix, as it's used in [doc/index.rst](https://raw.githubusercontent.com/spatialaudio/nbsphinx/b0542b404383e08c52574ea72ec318a941b4991d/doc/index.rst).

Using the file extension in the glob pattern doesn't seem to be supported by Sphinx itself. You'll get the same error if you use `*.rst`:

    WARNING: toctree glob pattern '*.rst' didn't match any documents

I think this would be a useful feature, but you should report this directly to the Sphinx team: https://github.com/sphinx-doc/sphinx/issues.

And about `_add_notebook_parser()`: You are right, we could change this now, but as long as there are no problems caused by my original hack, I'm not in a hurry to do this.

If you want to make a PR to replace this, go ahead!

**Comment by mgeier** [comment]
@ltalirz Did you report this to the Sphinx people?

**Comment by ltalirz** [comment]
> It should work without the .ipynb suffix, as it's used in doc/index.rst.

I don't know how, but somehow I missed this sentence. Thanks for the prompt help and sorry for not following up!

> I think this would be a useful feature, but you should report this directly to the Sphinx team

From their initial response it seems they don't want to introduce extension-based selectors in the glob pattern. If you still think it should be introduced, happy for you to reopen https://github.com/sphinx-doc/sphinx/issues/5756

**Comment by mgeier** [comment]
Thanks @ltalirz.

I've added a comment over there, for me this has low priority.

**Comment by mgeier** [comment]
For the record, it turned out that using the file suffix in a `toctree` directive is not recommended (and it only works for backwards compatibility).
