### ISSUE TITLE
Linking between notebooks in subdirectory

### ISSUE THREAD

**Issue by jgosmann** [spatialaudio/nbsphinx#168]
Linking between notebooks that are in the same subdirectory does not seem to work. The root directory for the documentation is `docs` and the notebooks are in `docs/examples`. I created links with `[text](./linked-file.ipynb)` and they work in Jupyter notebook. When building the docs I get warnings like
```
/home/jgosmann/Documents/projects/nengo_spa/docs/examples/intro_coming_from_legacy_spa.ipynb:8: WARNING: unknown document: /./linked-file
```
and no link is inserted in the built docs. If I change the link to `[text](examples/linked-file.ipynb)`, the warning disappears and a link is inserted, but it leads to `examples/examples/linked-file.html` which is the wrong location (apart from not working in Jupyter notebook).

**Comment by jgosmann** [comment]
This is with nbsphinx 0.3.1, sphinx 1.7.1, and Python 3.6.1.

**Comment by mgeier** [comment]
Thanks for the report.

AFAIK, there is no reason at all, ever, to prepend `./` to a local link.
This is an idiom that stems from the use in a shell where `./` can be prepended to an executable in the current directory to be able to execute it even if the current directory isn't in the `$PATH`.

Did you try it with the much simpler `[text](linked-file.ipynb)`?

I think this should be the canonical way to do it, but I'll still have a look if I can make it work with the (IMHO awkward) `./` in front of the link target, since this seems to be supported in Jupyter.

**Comment by jgosmann** [comment]
I actually tried `[text](linked-file.ipynb)` first and I had the same problem. There is definitely no reason that I need the `./` in front and I'd be happy to remove it if it worked.

**Comment by mgeier** [comment]
Can you please provide a sample project where `[text](linked-file.ipynb)` doesn't work?
It did work for me from the beginning, it works in the docs, and I would be really surprised if it didn't work.

**Comment by jgosmann** [comment]
This also happens in nengo/nengo_spa#68. [This](https://github.com/nengo/nengo_spa/blob/a32887dd4649dcff3cc6d419d3b93b9a3f176244/docs/examples/intro.ipynb) and [this notebook](https://github.com/nengo/nengo_spa/blob/a32887dd4649dcff3cc6d419d3b93b9a3f176244/docs/examples/intro_coming_from_legacy_spa.ipynb) are supposed to link each other. In both notebooks the link is right at the end of first paragraph. If I remove the leading `./` the warning looks like
```
/home/jgosmann/Documents/projects/nengo_spa/docs/examples/intro.ipynb:8: WARNING: unknown document: /intro_coming_from_legacy_spa
```
It seems that it is not taken into account that the linking notebook files are in subdirectories.

**Comment by mgeier** [comment]
... and I am indeed surprised!

I thought that inter-notebook links already work fine, but it turns out they don't.
With all the handling of subsection links, I somehow forgot to add the subdirectory to the links without subsections.

Can you please check if #171 fixes your problem?

**Comment by jgosmann** [comment]
It doesn't seem to fix the problem. I still get the same warnings and no links.

**Comment by mgeier** [comment]
Can you please double-check that you used the right `nbsphinx` version including #171, i.e. branch `issue-168`?

**Comment by jgosmann** [comment]
Arg, somehow there was the old version left next to the install of the Github branch. 😠 
Anyways, the problem is indeed fixed. :)

**Comment by kmuehlbauer** [comment]
@mgeier Sorry for ressurection of this issue. I've had the same problem, which is solved by this issue. When do you plan releasing this? I'm bound to use version from python index, can't use github master.

**Comment by mgeier** [comment]
Thanks for the reminder @kmuehlbauer, I was planning to make a release in the next few days.
I just merged #173 and I would like to wait 1 or 2 days if there are any complaints.

> I'm bound to use version from python index

OK, it'll be there soon ... but just in case: are you aware that you can use `pip` with a Github URL?

    python3 -m pip install git+https://github.com/spatialaudio/nbsphinx.git@master

This can also be used in `requirements.txt` and `environment.yml`, see http://nbsphinx.readthedocs.io/en/0.3.1/usage.html#Using-requirements.txt.

**Comment by kmuehlbauer** [comment]
@mgeier Thanks, actually I did try this first after posting here. Seems, that the correct nbsphinx version is installed this way. And, this works perfectly on my local install. All links are created.

Unfortunately on rtd, I have some strange effects going on while linking notebooks. So at some places the links are not created and I'm twisting my head around this. I'm not sure where to file an issue, because my application is a bit strange. So this here might be the most appropriate. 

Anyway here is the layout:
This is the [docs-rep](https://github.com/wradlib/wradlib-docs), where I pull in `conf.py` the [notebooks repo](https://github.com/wradlib/wradlib-notebooks) and for API the [library](https://github.com/wradlib/wradlib). Because of the long runtime and the c-library dependencies the notebooks are preprocessed in the source repo and the dependencies are *mocked*. Really almost everything concerning nbsphinx works perfect, even the links which generate from the API work perfect. 

So for [this notebook here](https://github.com/wradlib/wradlib-notebooks/blob/devel/notebooks/zonalstats/wradlib_zonalstats_classes.ipynb), this would be [the final output on rtd](http://docs.wradlib.org/en/latest/notebooks/zonalstats/wradlib_zonalstats_classes.html). In the last cell the link is not created on rtd, but locally it works.

**Comment by kmuehlbauer** [comment]
I'll test as soon as possible and report back, might have to wait until tomorrow.
