### ISSUE TITLE
'HTML5Translator' object has no attribute 'set_first_last'

### ISSUE THREAD

**Issue by clenk** [spatialaudio/nbsphinx#176]
I'm getting the following error in sphinx when using nbsphinx:

```
Exception occurred:
  File "/home/lu/.virtualenvs/test/lib/python3.6/site-packages/nbsphinx.py", line 1376, in visit_admonition_html
    self.set_first_last(node)
AttributeError: 'HTML5Translator' object has no attribute 'set_first_last'
```

The error only shows up when making epub output; html and latex are fine.

nbsphinx version: 0.3.2
Sphinx version: 1.7.0 (also tested 1.6.5 with same result)
docutils version: 0.14

If I lock the Sphinx version, `sphinx<1.6`, the error goes away.

See also: https://github.com/rtfd/readthedocs.org/issues/3148

**Comment by Juanlu001** [comment]
I was hit by this today as well:

https://readthedocs.org/projects/telluric/builds/7029356/

(and I also originally reported rtfd/readthedocs.org#3148)

**Comment by mgeier** [comment]
This happens for epub output because that uses the HTML5 builder (since Sphinx 1.6).

The same error can be provoked with HTML output by using the [html_experimental_html5_writer](http://www.sphinx-doc.org/en/stable/config.html#confval-html_experimental_html5_writer) option.

I've created #179, which doesn't use `set_first_last()` anymore.

@clenk, @Juanlu001 Can you please test if this works for you?

**Comment by clenk** [comment]
Seems to work for me!

**Comment by Juanlu001** [comment]
Cannot test this since it's an error with Read the Docs, but it's also epub so looking forward to it :) Perhaps can we have a release soon-ish?

**Comment by mgeier** [comment]
> Perhaps can we have a release soon-ish?

See https://github.com/spatialaudio/nbsphinx/pull/178#issuecomment-382050380.

**Comment by clenk** [comment]
@Juanlu001 I tested it locally by running `make epub` in my docs folder. It's basically what RTD does.

**Comment by Juanlu001** [comment]
It fixed the issue. Thanks @mgeier!
