### ISSUE TITLE
Include notebook inside a RST document

### ISSUE THREAD

**Issue by AntoineZen** [spatialaudio/nbsphinx#181]
I find this extension a great idea as use both Shpinx and Jupyter notebooks. But I prefer to write the most of the documentation in RestructedText as i find it more convenient and powerful than the markdown in the notebooks. 

So I'm not very convinced using `toctree` directive to include notebooks inside my documentations. It doesn't allow me to organize my document the way I want. Is there a way to include it in a manner like the `include` ([doc](http://docutils.sourceforge.net/docs/ref/rst/directives.html#include)) docutils directive does ? If not, do you think it will be feasible to add a new directive to do this within this extension ? I can implement it, if you think it is feasible and make sens.

**Comment by mgeier** [comment]
See the discussion in #33 for some problems with this approach.
If you know a way around those problems or if you know a different approach that doesn't have those problems, feel free to make a PR!

**Comment by AntoineZen** [comment]
So I had a look at #33. I seems to do what I want. The problem mentioned are with notebooks outside the Sphinx source tree, if I am right. This is realized by extension nbsphinx-link. Good. 

Then why not  taking option 4 in [this comment](https://github.com/spatialaudio/nbsphinx/pull/33#issuecomment-207795147) so we can have the `nbinclude` directive for the one who need it with the constraint to have notebook in Sphinx source tree? Do you think it's valid ?

**Comment by mgeier** [comment]
I don't know. Option 4 sounds a bit restrictive. I'm quite sure people will start asking to lift this restriction.

Can you please describe how you would use this feature?
Would you have multiple Jupyter notebooks in one Sphinx page?
What kind of content would you have before/between/after the notebooks?

**Comment by mgeier** [comment]
Another question: Wouldn't make https://github.com/ngoldbaum/RunNotebook more sense in your case?

**Comment by AntoineZen** [comment]
Lot of questions here! I answer it down-bellow

**Can you please describe how you would use this feature?**
I'm an embedded software developer. I use Sphinx a lot to document my project. Those project are mainly code, where Sphinx excel for documentation. But sometimes have signal processing or analog circuit that need to be described with math and I like to demonstrate it with IPython/numpy/matplotlib. There Jupyter notebooks are great tools! 

So I prefer to work manly with RestructuredText, because it has many feature Jupyter notebooks lacks (thinks of cvs-table import, auto-doc, reference). Also it does enforce me to use a tool like Jupyter does, I can use my Favorit text-editor and be more productive. But I like to illustrate my theoretical explanation with notebook examples. If i use the toc-tree directive to include the notebook inside my RestructuredText, it break the chapter flow, by putting a table-of-cotent in the middle of my text ! 

**Would you have multiple Jupyter notebooks in one Sphinx page?**
Yes, for sure. I have a large chapters, where I want to include notebooks for each examples.

**What kind of content would you have before/between/after the notebooks?**
Text with math equation, Code example, code documentation. Just anything Sphinx allows.

**Wouldn't make https://github.com/ngoldbaum/RunNotebook more sense in your case?**
I was not aware of it, thanks ! I just tested it with my document.
Yes, in the sens of the `notebook` directive it provides. **But**, this extension has the following major flaw:

 - It does not support LaTeX output !
 - It does not support inline math.
 - The HTML output looks bad (sorry).

In that, your extension does a much better work ! 

Maybe it would be easier and make more sens to make a new extension that has the same features as  https://github.com/ngoldbaum/RunNotebook but use your extension under the hood to do the rendering. What do you think ?

**Comment by mgeier** [comment]
Thanks for the answers, that's very interesting!

So you basically like to use Jupyter notebooks like other people would use code blocks with some comments for explanations?

I think this could actually be a meaningful feature, something like a "fancy code block".

I think for this use case, the content of a notebook should somehow be separated from the surrounding text, e.g. by putting it in some kind of a box (in both HTML and LaTeX output), similar to how code blocks are displayed.

This could be probably handled in a way similar to `nbsphinx_prolog` and `nbsphinx_epilog` (http://nbsphinx.readthedocs.io/en/0.3.2/prolog-and-epilog.html), but in this case I would draw a box by default. But users could, if they want, also add the notebook file name or some other fancy stuff. Or they could remove the box if they don't like it.

I'm not sure what should happen with section headings ... should they become part of the Sphinx TOC?
I guess not ...

There are many other open questions and there will be a lot of work to do, but what do you think so far?

> Maybe it would be easier and make more sens to make a new extension that has the same features as https://github.com/ngoldbaum/RunNotebook but use your extension under the hood to do the rendering. We would have best of both world. What do you think ?

I don't think that would work.
The two extensions are fundamentally different in that `nbsphinx` uses Sphinx/docutils to generate the page content, while RunNotebook uses external tools. Because of this, the way the content is embedded into the rest of the Sphinx stuff is quite different.
But if you want to try to implement such a new extension, go ahead!

BTW, you should also have a look at the other alternatives listed in http://nbsphinx.readthedocs.io/en/0.3.2/links.html.
If you find something else that's not listed there, please let me know.

**Comment by mgeier** [comment]
@AntoineZen Any news?

**Comment by AntoineZen** [comment]
Yes, I ended doing a small hack, but I does what I wanted. I't basically the same thing that the "RunNotebook" extension, but it works with Latex! 

What I do is that I call "nbconvert" using the Makefile before running sphinx. It exectue and convert the notebook to RestructuredText. (Here is the command for refence: `jupyter-nbconvert --execute my_notebook.ipynb --to rst`) Then I just include the produced output in my document using the include directive `.. include: my_notebook.rst` .  Works like a charm. But the Python code does not as good as with your extension, it just a regular "code-block". 

Thanks for you support !

As my problem is solved, I close the case.
