### ISSUE TITLE
Nicer display of pandas dataframes in nbsphinx

### ISSUE THREAD

**Issue by gansanay** [spatialaudio/nbsphinx#182]
Hi,

I may have missed something but... I can't get pandas dataframes to display in nbsphinx generated docs as nicely as they display in jupyter notebook. I get an ugly large font in an ugly black and white table.

Is it just a CSS issue?

Regards,
Guillaume

**Comment by mgeier** [comment]
Can you please provide an example notebook and screenshots for the "nice" and "ugly" cases? Please also provide a screenshot how it looks when using `nbconvert`.

**Comment by gansanay** [comment]
Of course. This is "nice":

![image](https://user-images.githubusercontent.com/3726359/38987966-e45f43c4-43d1-11e8-8e63-b790fb10b19d.png)

This is "ugly":

![image](https://user-images.githubusercontent.com/3726359/38987997-fc9304b2-43d1-11e8-8e18-b9bdb06d2680.png)

Downloading from jupyter notebook as HTML (nbconvert) leads to the "nice" version.

Sample notebook: https://gist.github.com/gansanay/34363886efeb3e7c958a281811c14822

**Comment by mgeier** [comment]
Interestingly, when calling `nbconvert` directly, the result looks more like the "ugly" version.

I think this is only a matter of which CSS is included.

You can add whatever CSS you like to your Sphinx configuration.

Or, if you think some CSS should be added directly to `nbsphinx`, feel free to make a PR for it.
But I think it makes more sense to first discuss this in the context of `nbconvert`, then `nbsphinx` can simply take the CSS from there.

**Comment by mgeier** [comment]
@gansanay Were you able to get "nice" dataframes in the end?

**Comment by eotp** [comment]
I have the same issue. Looking [here](https://github.com/jupyter/help/issues/283) I found that this behavior is related to nbconvert versioning.  

By using nbconvert (version 5.3.1) directly with `<link rel="stylesheet" href="https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css">` in a Raw NBConvert type cell (as suggested [here](https://github.com/jupyter/help/issues/283) ) works well; I get a nicely rendered dataframe in the html output.  However, using nbsphinx on the same notebook still gives the old ("ugly") rendering. :-(

I even tried to provide a custum .css file (as shown [here](http://docs.readthedocs.io/en/latest/guides/adding-custom-css.html)), using https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css; this did not work either.

**Comment by mgeier** [comment]
You should be able to load the CSS file in your `conf.py` with

```python
def setup(app):
    app.add_stylesheet(
        'https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css')
```

In the upcoming Sphinx 1.8.0 release, this can also be done with

```python
html_css_files = ['https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css']
```

The bad news, however, is that this doesn't seem to work well with the Sphinx and `nbsphinx` styling.

If you want to improve the situation, please make a PR that puts a copy of the official Jupyter Notebook CSS (I guess for the `dataframe` class?) into the `CSS_STRING` variable.

**Comment by PedroRegisPOAR** [comment]
I tried the solutions proposed by @mgeier, but none worked. I dont know how to do some workaround nor help to build a solution.

I tried both versions 5.1.0 and [5.4.0](https://github.com/jupyter/nbconvert/blob/master/setup.py#L70) : 

```
html_css_files = ['https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css']
```
and
```
html_css_files = ['https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css']
```
and, both of this too:
```
def setup(app):
    app.add_stylesheet(
        'https://cdn.jupyter.org/notebook/5.1.0/style/style.min.css')
```
and 
```
def setup(app):
    app.add_stylesheet(
        'https://cdn.jupyter.org/notebook/5.4.0/style/style.min.css')
```
This  `setup` function have to be invoked? I just pasted it in the conf.py file.


The results of use nbconvert and nbsphinx are bellow:

nbconvert:
![nbconvert-croped](https://user-images.githubusercontent.com/20312381/47059991-0692ef00-d1a2-11e8-89c7-c80f70b04786.png)

nbsphinx:
![nbsphinx-croped](https://user-images.githubusercontent.com/20312381/47060440-f11ec480-d1a3-11e8-88c1-00cb98d1dc0e.png)

Another stuff that I noticed were that the colors of many things, import line, strings, and numbers are different too. I guess that it is because the css problem too?

The versions of the libraries that I am using:
pandoc 1.17.2

Sphinx==1.8.1
nbsphinx==0.3.5
jupyter==1.0.0
pandas==0.23.4
nbconvert==5.4.0

**Comment by mgeier** [comment]
I've added some CSS definitions in #228, can you please check if that works for you?

If you find some missing CSS definitions, please tell me.

**Comment by PedroRegisPOAR** [comment]
Sorry for the late answer. I tested now and the issue still happening.

How do you test that you have solved the problem?

How can I help you find why I still face the issue?

I use Docker and for help to find where the problem is I have put every thing in a [github repository](https://github.com/spatialaudio/nbsphinx/pull/228) to try help you figure out why the problem still happening.

**Comment by mgeier** [comment]
@PedroRegisPOAR Have you used the `master` branch? Please note that the changes from #228 are not yet in a released version of `nbsphinx`.

You should try to install `nbsphinx` from the Git repository, as described in [CONTRIBUTING.rst](../blob/master/CONTRIBUTING.rst), or you can install it with `pip` like this:

    python3 -m pip install git+https://github.com/spatialaudio/nbsphinx.git@master
