### ISSUE TITLE
WARNING: Pygments lexer name 'ipython3' is not known

### ISSUE THREAD

**Issue by ostrokach** [spatialaudio/nbsphinx#24]
I get thousands of warnings:

```
WARNING: Pygments lexer name 'ipython3' is not known
```

when I run `make html` after adding `'nbsphinx'` to `extensions`. 

This happens even with an empty `index.rst` file (it seems to find my `.ipynb_checkpoints` folder).

---

```
python 3.5.1
ipython 4.1.1
nbconvert 4.1.0
jupyter 1.0.0
pygments 2.1
```

**Comment by mgeier** [comment]
Hmm, for me this has always worked; the lexer should be part of the "IPython" package: http://ipython.readthedocs.org/en/stable/development/lexer.html.

Can you try to re-install this package?

> This happens even with an empty `index.rst` file (it seems to find my `.ipynb_checkpoints` folder).

Yes, Sphinx searches the whole source directory (including subfolders) for notebook files and parses all of them, regardless of what's in your `index.rst`. You should probably add something like this to your `conf.py`:

```python
exclude_patterns = ['_build', '**.ipynb_checkpoints']
```

See http://nbsphinx.readthedocs.org/en/latest/usage.html.

**Comment by ostrokach** [comment]
I had to add `'IPython.sphinxext.ipython_console_highlighting'` to `extensions`. Somehow the [old IPython docs](https://ipython.org/ipython-doc/3/api/generated/IPython.sphinxext.ipython_directive.html)  have this info but the new ones don't.

Adding `'**.ipynb_checkpoints'` to `exclude_patterns` fixed the other problem.

Thanks!

**Comment by mgeier** [comment]
Good to know that you found a solution that works for you!

But still, IMHO the `ipython3` lexer should work automatically.
I've never used `ipython_console_highlighting` (or anything else) explicitly and it just works.
I think this should be somehow be automatically registered when installing the `IPython` package.

**Comment by nehalecky** [comment]
FWIW: I'm also hitting this same warning when building the documentation of the the `nbsphinx` repo. After cloning and installing dependencies, I run `sphinx-build -b html doc doc/html` whilc checked out to version `0.2.8`.

The fix proposed by @ostrokach :
> I had to add 'IPython.sphinxext.ipython_console_highlighting' to extensions in my conf.py. 
also worked for me, warnings are gone. 

Thanks!

**Comment by michaelaye** [comment]
The advise of 
> adding 'IPython.sphinxext.ipython_console_highlighting' to extensions in my conf.py
is not in the installation instructions yet, should it be added? I also receive this warning
```bash
/Users/klay6683/Dropbox/src/pyciss/docs/examples.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known
```
multiple times for a single almost empty notebook.

**Comment by mgeier** [comment]
@michaelaye If you get the warning even if you have the `ipython` package installed, this is IMHO a bug in its installation procedure. I'm re-opening this issue as a reminder.

Adding the `IPython.sphinxext.ipython_console_highlighting` extension is only a work-around, but not the real solution of the problem.

We can add a hint regarding the work-around to the docs (feel free to make a PR!), but it would be also very good to find the actual cause for the problem (and solve it).

**Comment by adrn** [comment]
I'm getting the same warnings. I set up a fresh conda environment, installed all packages as described in http://nbsphinx.readthedocs.io/en/0.2.12/usage.html 

What do you mean by "a bug in its installation procedure"?

**Comment by mgeier** [comment]
> What do you mean by "a bug in its installation procedure"?

expected behavior:
1. install the `ipython` package
2. the `'ipython3'` lexer is available without additions actions to be taken

your observed behavior:
1. install `ipython`
2. the `'ipython3'` lexer is not available

Therefore, I suspect there is a bug somewhere.
I don't know how the "registration" process of the lexer is supposed to work, but it definitely shows different behavior on different systems.

For me, on Linux/Debian shows the expected behavior.
It works also for the automatic build on readthedocs.

**Comment by mgeier** [comment]
So the reason might be a buggy Anaconda package: https://github.com/ContinuumIO/anaconda-issues/issues/1430

**Comment by jnquintin** [comment]
It took me a while to get rid of the same issue but on rhel7.

It may help others, the solution may be deeper than that but by installing qtconsole for (python2.7 since I am on rhel7) to install the file:
/usr/lib/python2.7/site-packages/qtconsole/pygments_highlighter.pyc 
with the line:
from ipython_genutils.py3compat import PY3, string_types

After the installation, the lexer for ipython3 was here.

I hope it may help to change the packaging and/or other users.

**Comment by mgeier** [comment]
I'm not sure if the Anaconda package is still broken, but this can definitely be solved by using the `conda-forge` channel.

**Comment by timothydmorton** [comment]
FWIW, I have not had problems with syntax highlighting in nbsphinx when I build locally, but I hit this problem when building with nbsphinx on readthedocs.  Not sure if this is helpful or not.

**Comment by timothydmorton** [comment]
OK, looks like I just needed to add ipython to the requirements.txt; didn't need to add the extension referenced above.

**Comment by mretegan** [comment]
The port version on macOS gives the same error. The one installed from pip works fine.

**Comment by adamjstewart** [comment]
I know this issue is ancient, but I just encountered the same problem on ReadTheDocs with all the latest versions. A simple `pip install sphinx nbsphinx` doesn't install ipython, so I end up with the warning message:
```
foo.ipynb:: WARNING: Pygments lexer name 'ipython3' is not known
```
If I also install ipython, the warning message changes:
```
WARNING: nbsphinx_widgets_path not given and ipywidgets module unavailable
```
So it seems like either ipywidgets is required, or `nbsphinx_widgets_path` must be set. Should ipywidgets be listed as a required dependency, or is this an optional dependency only needed for the ipython lexer?

**Comment by mgeier** [comment]
@adamjstewart 

`ipywidgets` should only be required if there are widgets in the notebooks, more specifically, if there is some `application/vnd.jupyter.widget-state+json` data.

If you have widgets, you somehow have to provide the appropriate JavaScript files, which is done automatically if `ipywidgets` is available or manually with `nbsphinx_widgets_path`, see https://nbsphinx.readthedocs.io/en/0.8.9/code-cells.html#Interactive-Widgets-(HTML-only).

If none of your notebooks has any widgets but the warning is still shown, please let me know, because that may be a bug.

And yes, if you want to have code highlighting in code cells, you'll have to install IPython, see https://nbsphinx.readthedocs.io/en/0.8.9/installation.html#Pygments-Lexer-for-Syntax-Highlighting.

**Comment by Bilokin** [comment]
Hello, I have the same issue as @adamjstewart and my code highlight in the jupyter pages doesn't work and it broke a few days or weeks ago. 
Example: https://syscorrfw.readthedocs.io/en/latest/particleid_weight_production.html
Is this issue already being worked on?
Which steps should I take to resolve it for my package?

**Comment by mgeier** [comment]
A new issue appeared very recently, see #687.

**Comment by kijinosu** [comment]
> I never had this issue until now with sphinx9:
> 
> `Pygments lexer name 'ipython3' is not known [misc.highlighting_failure]`
> 
> Looks like some dependency dropped including ipython and I need to manually install it now..? Using `pip install ipython` did help here.

I am having the same problem, with the same solution, except that I have to run `pip install ipython` every time I modify an .ipynb file.  (BTW, Running Sphinx v8.2.3)
