### ISSUE TITLE
Section numbering gets wrong when sections have the same titles

### ISSUE THREAD

**Issue by chrismedrela** [spatialaudio/nbsphinx#262]
When there are two sections with the same title, the number for the first one is the same as the one for the second section.

Example markdown cell:
```markdown
# Title
## Normal
## Duplicated
## Duplicated
```

The output is:

```
1. Title
1.1 Normal
1.3 Duplicated
1.3 Duplicated
```

Note that there is no 1.2 section. Instead, there are two 1.3 sections.

Environment info:
- OS: Mac
- Python version: 3.6.4
- Sphinx version: 1.8.2
- nbsphinx 0.3.5

This bug doesn't happen when you create a test .rst file, so it must be something wrong with nbsphinx, not sphinx.

**Comment by mgeier** [comment]
Thanks for the report!

Can you please provide a minimal example project?

**Comment by chrismedrela** [comment]
@mgeier do you mean sth like [that](https://gist.github.com/chrismedrela/d1ee4feebb5e5186a423094a25673739)?

**Comment by mgeier** [comment]
Yes, exactly. Plus a minimal Sphinx configuration (`conf.py`). Plus a description how you ran Sphinx to get your output.

In short, a simple way for me to reproduce your problem.

**Comment by mgeier** [comment]
Thanks, I can reproduce it now!

I assume this is because of this custom `nbsphinx` transform:

https://github.com/spatialaudio/nbsphinx/blob/345f406e6f98d584fa493c788099e68b218f3a30/src/nbsphinx.py#L1333-L1347

This is needed because otherwise the section anchors in the HTML output wouldn't match the anchors in the Jupyter notebook application.

However, this seems to have this weird effect on section numbering ...

I'll have to look into this.

**Comment by mgeier** [comment]
PR #270 should fix this, but I'm not yet satisfied with the details of it ...
