### ISSUE TITLE
how to install the latest?

### ISSUE THREAD

**Issue by aaronmarkham** [spatialaudio/nbsphinx#300]
I've been running in circles here trying to install master or the recent commit that gets rid of those pandoc warnings. How do you do it? It seems no matter what I try I'm stuck with 0.4.2.

**Comment by aaronmarkham** [comment]
Figured it out - the warning arises in nbsphinx, but the cause is nbconvert. The [fix I was looking for was in master on nbconvert](https://github.com/jupyter/nbconvert/pull/964). Also, even though the version states 0.4.2 or whatever after you install from source, the actual version is whatever you installed (what branch/version is active), and the version number is mis-reporting at that point. I wish it didn't work that way as this creates a lot of frustration and confusion. 🤷‍♂️

**Comment by mgeier** [comment]
I'm glad that you found the cause of the problem!

> Also, even though the version states 0.4.2 or whatever after you install from source, the actual version is whatever you installed (what branch/version is active), and the version number is mis-reporting at that point.

Yes, that is intentional.
When using a version directly from the Git repository, the `__version__` information is invalid and should be ignored.
When you use a released version, everything should be fine.

> I wish it didn't work that way as this creates a lot of frustration and confusion.

This is the first time I've heard about anyone having problems with that.

I *could* change the `__version__` attribute (to something with `dev` or whatever in the name) each time after a release, but this would be additional work for me (and additional potential for making mistakes).
Also, even if I would change the `__version__` attribute, it would still be wrong to have a single version for all development steps between releases. So I would have to change the version in each commit. Do you really want me to do that?
I could of course completely remove the version information between releases, but I doubt this would be helpful, right?

**Comment by aaronmarkham** [comment]
Most people probably don't pip install from source. They use tagged versions, so it never comes up. I have only rarely done it with MXNet, but I think because we increment the version after a tag release you at least get it to say something different (one minor release up). That way you have a visual indication that what you just installed is, in fact, different than what's up on pypi as the latest release. Maybe that's a kind of "best practice". I'm not sure though.
Here's what we have for [version (1.5.0)](https://github.com/apache/incubator-mxnet/blob/7485a78372b4a20211105b19e27a0549061ee688/python/mxnet/libinfo.py#L114), but our most recent tag is 1.4.0. So if you pip install from source it'll output 1.5.0 instead of 1.4.0.

**Comment by mgeier** [comment]
> Maybe that's a kind of "best practice". I'm not sure though.

I've seen several times that maintainers add something like `.dev` to the just released version.

```pycon
>>> import IPython
>>> IPython.__version__
'7.5.0.dev'
```

Matplotlib, for example, has a very fancy method to get the development version from git:

```pycon
>>> import matplotlib
>>> matplotlib.__version__
'3.0.2.post2132+gf58c9339e'
```

I think this is nice, I just don't want to add such a huge amount of code just for something as irrelevant as the development version number.

I don't understand how your method works:

If you change the version to `1.5.0` after releasing `1.4.0`, doesn't that preclude any micro updates (like `1.4.1`, `1.4.2` etc.)?

And what happens when you actually release `1.5.0`?
Then you have the exact same problem as I'm having, just shifted by one version number ...

**Comment by aaronmarkham** [comment]
Hey Matthias, sorry I missed your question here. Not saying this is the best way (sounds like matplotlib has probably the most accurate thing), but here you go:
Master has the next up minor version, so when you put out 1.4.0, you increment master up to 1.5.0. Then if you need to do a patch release you do this out of a 1.4.x branch. Cherry picking whatever patches you want on top of a cut of 1.4.0. Then master still slowly builds up stuff while reporting it's "1.5.0". It's kind of manual but adds some clarity to the situation.

**Comment by mgeier** [comment]
OK, I see, if you have a 1.4.x release branch, it probably makes sense to pre-assign 1.5.0 to the `master` branch. Except that it is still completely wrong and not much less wrong than my approach. Now you have many versions 1.5.0 which are all different, while I would have many versions 1.4.x which would also be different.

And I think you would still have my problem within your release branch, right?
Or does each commit in your release branch update the micro version number?

Probably your approach makes more sense if you have release branches, and mine if you don't?

Either way, you shouldn't rely on version numbers between releases, except if you have a fancy Git-based system in place like Matplotlib does.
