### ISSUE TITLE
How do I link to API docs from a notebook?

### ISSUE THREAD

**Issue by rabernat** [spatialaudio/nbsphinx#308]
We use autodoc to generate our API docs. I would like to link to these docs from a notebook built by nbsphinx. I read the documentation and examples carefully, but I can't figure out how to do it.

In rst, the reference looks like:
```
:py:func:`xarray.plot.line`
```

I would also like to be able to use reference directives like:
```
:ref:`plotting.multiplelines`
```

What should I put in my notebook markdown cell to produce such links?

Thanks for the great package.

**Comment by mgeier** [comment]
The mentioned syntax is not supported in Markdown cells, but if you want you can use it in [raw reST cells](https://nbsphinx.readthedocs.io/en/0.4.2/raw-cells.html#reST). This should look fine in the generated docs, but if you open the notebook in Jupyter, it tends to look not so nice.

If you want to keep using Markdown cells, links to API docs should work like shown in https://nbsphinx.readthedocs.io/en/0.4.2/markdown-cells.html#Links-to-Domain-Objects.

I'm not sure, however, if this also works with `autosummary`. You should try something like this:

    [xarray.plot.line()](generated/xarray.plot.line.rst#xarray.plot.line)

Instead of the `:ref:` link, you can try using the auto-generated header ID (you'll have to manually insert the text of the heading):

    [Multiple lines showing variation along a dimension](plotting.rst#multiple-lines-showing-variation-along-a-dimension)

See also https://nbsphinx.readthedocs.io/en/0.4.2/markdown-cells.html#Links-to-*.rst-Files-(and-Other-Sphinx-Source-Files).

If you have ideas for improving this situation, I'm open for suggestions and pull requests!

**Comment by rabernat** [comment]
Thanks I think it is clear now! I didn't understand how to use an RST cell. But your docs are in fact very clear about this.
