### ISSUE TITLE
missing headings; some at wrong level?

### ISSUE THREAD

**Issue by nickeubank** [spatialaudio/nbsphinx#373]
When rendered, I'm losing some of my headings, and others are being rendered at the wrong level. For example, here's my notebook:

![image](https://user-images.githubusercontent.com/9683693/72013680-5ab54380-322c-11ea-92cb-1257a81de2a8.png)

And here's the build: 

![image](https://user-images.githubusercontent.com/9683693/72013711-6acd2300-322c-11ea-8200-9c75eb17ba09.png)

Also others are at the wrong level -- this should be H3:

![image](https://user-images.githubusercontent.com/9683693/72013743-79b3d580-322c-11ea-9c7c-3c0dbed6babd.png)

But it's H4:

![image](https://user-images.githubusercontent.com/9683693/72013777-8c2e0f00-322c-11ea-81a4-780b7c30d2b8.png)

Attaching ipynb and html:

[Archive.zip](https://github.com/spatialaudio/nbsphinx/files/4037088/Archive.zip)

(This seems distinct from other "heading" issues?)

EDIT: Add versions:

```
nbsphinx                  0.5.0                      py_0    conda-forge
sphinx                    2.3.1                      py_0    conda-forge
sphinx-markdown-tables    0.0.9                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
```

```

**Comment by mgeier** [comment]
Thanks for the report!

Have you noticed the warnings generated by Sphinx?

```
taxonomy_of_questions-Copy1.ipynb:122: WARNING: Title level inconsistent:

Why Causal Inference is Hard
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taxonomy_of_questions-Copy1.ipynb:171: WARNING: Title level inconsistent:

Prediction Based on Causal Methods
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
taxonomy_of_questions-Copy1.ipynb:184: WARNING: Title level inconsistent:

Prediction Based on Supervised Machine Learning
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is caused by the peculiar way how Sphinx/`docutils` handles heading levels.

Sphinx doesn't have "absolute" heading levels. The resulting levels are determined by how you are nesting them.
And if you are not consistent in your usage, the result might not be as expected (and there might be a warning).

It might be possible to work around this behavior to some degree (but I don't know how), but I'm not sure if it's worth the trouble.

If you have suggestions for how to improve the situation, please speak up!

> This seems distinct from other "heading" issues?

https://github.com/spatialaudio/nbsphinx/issues/22#issuecomment-188890119
https://github.com/spatialaudio/nbsphinx/issues/53#issuecomment-228117445 and https://github.com/spatialaudio/nbsphinx/issues/53#issuecomment-228396287

Please make all Sphinx warnings disappear, and if the problem still persists, please post an update here.

There has been a different issue regarding headings, but I don't know if it is relevant here: #55.

**Comment by nickeubank** [comment]
Oh! I had not seen that - I was using auto billed to the error messages must have scrolled by too quickly. Will dig in!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nickeubank** [comment]
Yup, that was it! Thanks for the help, and sorry for not catching that myself.

**Comment by mgeier** [comment]
No problem! I know that this behavior is not entirely obvious ...
