### ISSUE TITLE
Unexpected behaviour when a notebook is not valid JSON

### ISSUE THREAD

**Issue by pbugnion** [spatialaudio/nbsphinx#374]
Thanks for nbsphinx. It's great!

When a notebook is not valid JSON, the JSON source gets directly rendered to HTML.

As far as I can tell, this behaviour arises [here](https://github.com/spatialaudio/nbsphinx/blob/master/src/nbsphinx.py#L834): if the default converter fails for any reason, nbsphinx falls back silently to the RST Parser. The RST Parser seems to just convert the content, broken JSON and all, to HTML.

Unless I'm missing something, I'd expect nbsphinx to fail if it fails to parse the notebook?

I've created a minimal repository demonstrating this [here](https://github.com/pbugnion/nbsphinx-with-broken-notebook). With this, the rendered HTML looks like:

<img width="1277" alt="Screenshot 2020-01-09 at 16 50 08" src="https://user-images.githubusercontent.com/1392879/72087311-2743e900-3300-11ea-8ae2-8eba658ddffc.png">

This tripped us up in ipywidgets when a notebook became invalid JSON as a result of a merge conflict. Reported [in this issue](https://github.com/jupyter-widgets/ipywidgets/issues/2702).

**Comment by pbugnion** [comment]
Very happy to implement a change to nbsphinx, if need be, once the maintainers have decided on the right course.

**Comment by mgeier** [comment]
Thanks for the report!

This is actually known behavior but I'm aware that it's a bit unfortunate.

The reason why this is not an error is that the `NotebookParser.parse()` method has two different tasks to do: (1) parse a whole input document, (2) parse a single translated sentence/paragraph.

See the docstring:

https://github.com/spatialaudio/nbsphinx/blob/aad12aa16c379300ba2cc99a9efcb432a1aaf2e6/src/nbsphinx.py#L822-L832

... and this issue + PR: #154 + #156

> I'm very happy to implement a change to nbsphinx myself

If you find a reliable way to detect that a given string is *not intended* as a reST (or in the future probably a Markdown) string, we could probably raise a combined `NotebookError` to get a proper error instead of a nonsensical output HTML.

There has also been a bit of a discussion on the Sphinx-dev mailing list: https://groups.google.com/d/topic/sphinx-dev/PvAQfZcDeHw/discussion

I think ideally Sphinx would create a separate API for translating paragraphs, then this problem would immediately go away. But I don't know whether that will happen anytime soon (or at all).

**Comment by mgeier** [comment]
As a work-around, you could turn Sphinx warnings into errors with `-W`: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#id6

It is quite likely that a garbled JSON file will cause quite a few warnings. It most definitely does in this case.

I'm normally using `-W` in CI, which helps finding problems early.

**Comment by pbugnion** [comment]
Ah thanks for the explanations. That makes sense. I'd read that part of the docstring, but I hadn't quite figured how it applied to my issue.

Thanks for the suggestion of using `-W`. You're definitely right that there were lots of warnings in that case.
