### ISSUE TITLE
wrapping long output 

### ISSUE THREAD

**Issue by kmuehlbauer** [spatialaudio/nbsphinx#40]
How can long output be wrapped correctly?

In some notebooks I print long lines, which extend over the screen (see rendered html here: http://wradlib.org/wradlib-docs/latest/simple_plot.html). How can it be done, that the lines are wrapped at the "end" of the code-boxes?

JFTR, the notebook is rendered with `runipy` and then sphinxed `nbsphinx`. Great tool, btw.

**Comment by mgeier** [comment]
There's simply some CSS missing, see #11.
I only used a minimal amount of CSS and was hoping that someone who knows more than me about CSS and browser compatibility stuff would fill in the rest ...

You can have a look at the CSS that is used by The Jupyter Notebook/`nbconvert`/nbviewer.jupyter.org and try adding some of it to `CSS_STRING` in `nbsphinx.py`.

I'd very much appreciate a PR for that!
But please only add things that actually make a difference and don't add anything that's only necessary for Internet Explorer < 11 (because that's not even supported anymore by Microsoft!).

> the notebook is rendered with `runipy`

Why, if I may ask?
Wasn't it possible to run it during the Sphinx build process via `nbsphinx`?

**Comment by kmuehlbauer** [comment]
Thanks for the pointers. No, no fancy IE stuff, just simple linebreaks for my firefox. I just see that `chromium` adds a scrollbar to that output. That would also be OK.

We render with `runipy` because we make further use of the rendered output file. And, we wanted to keep the rendering decoupled from sphinxing, also because of our workflow.

I will definitely have a look into this CSS, asap.

**Comment by kmuehlbauer** [comment]
Hopefully #42 can be used to wrap overly long lines.
