### ISSUE TITLE
toctree header is being replaced with notebook.ipynb header

### ISSUE THREAD

**Issue by datalifenyc** [spatialaudio/nbsphinx#427]
I have a list of toctree files in my index.rst. 

```
.. toctree::
   :maxdepth: 2
   :caption: Table of Contents
   :name: mastertoc

   pages/README.rst
   pages/summary.rst
   pages/code_files.rst
```

The **code_files.rst** has sections, subsections, subsubsections, and paragraphs. Within code.rst, I reference a **clean_data.ipynb** notebook (located in a different parent directory). When I click on the link for clean_data.ipynb notebook, it's header and sub-headers replace the tree structure of code_files.rst in the Table of Contents. My objective is to have the jupyter notebook appear as a subsubsection within the code_files section of the Table of Contents. 

Do you know what I may be missing to create this behavior?

Thank you for the assistance.

**Comment by mgeier** [comment]
TBH, I can't quite follow.

Could you please provide a minimal example that shows the problem?

**Comment by datalifenyc** [comment]
> 
> 
> TBH, I can't quite follow.
> 
> Could you please provide a minimal example that shows the problem?

Thanks for getting back to me. I will put together an example and post it tomorrow.

**Comment by datalifenyc** [comment]
[Demo files](https://github.com/datalifenyc/demos/tree/master/rst)

I'm still trying to get an understanding of the hierarchy for headings in RST. The last heading used in an rst file seems to affect whether the following RST file appears in the Table of Contents. 

Basketball >> Professional >> Teams >> Houston
1. How do I get the TOC to expand for the subheadings under team name, **Houston**? The first level headings for the Jupyter Notebooks only appear when I click on the link, **Get 1996 Data**. 

Houston
|__1996 Player Stats
|__1995 Player Stats

If I were to click on **Get 1995 Data** instead, both "1996 Player Stats" and "1995 Player Stats" no longer appear in the Table of Contents.

Houston

**Comment by mgeier** [comment]
The TOC depth is limited by the theme you are using.

This should fix it:

```python
html_theme_options = {
    'navigation_depth': 5,
}
```

Of course you can also use a higher number or `-1`.

If you would use another theme, you would run into different problems:

1. You are using `:maxdepth: 4` in your top-level `toctree`, but your "Player Stats" are in level 5.
1. You are using `:hidden:` in the basketball `toctree`, which would also hide the sections in the toctree in some themes (see also https://github.com/sphinx-doc/sphinx/pull/7443, which I happened to create a few days ago, which might add a `globaltoc_includehidden` option for most themes)

**Comment by datalifenyc** [comment]
Thanks for the suggestions. Based on your feedback, I think I'm almost there. 

1. The entire TOC appears on the index page with the expected hierarchy.

![sphinx_demo_toc_index_page](https://user-images.githubusercontent.com/57526824/79272925-2034f580-7e70-11ea-88c6-d93e917ed9c6.png)

However:

1. When I click on "1996 Player Stats" or "1995 Player Stats", the left sidebar displays these notebooks as top level headings, rather than under Houston.

![sphinx_demo_toc_sidebar_houston_player_stats](https://user-images.githubusercontent.com/57526824/79273328-d4cf1700-7e70-11ea-81c3-1c59a76927fc.png)

2. When the "1996 Player Stats" or "1995 Player Stats" is expanded in the left sidebar, if I click on the expand/collapse icon, it won't collapse. It only collapses when I select another header.

![sphinx_demo_toc_sidebar_collapse_button](https://user-images.githubusercontent.com/57526824/79273993-d947ff80-7e71-11ea-9d23-35d4e829fee5.png)

**Comment by mgeier** [comment]
This looks very much like a problem of the theme. Probably it just can't handle such deep nesting?

I also tried it with the `master` version of https://github.com/readthedocs/sphinx_rtd_theme, and it looks different, but I guess it still doesn't work 100%.

> Is that because of the header designations in the jupyter notebook?

I don't know what exactly you mean by that, but any subsection structure you can create with Jupyter notebooks, you can also create with normal RST files.

I recommend that you create a fresh minimal example, without using `nbsphinx` or any other extension, that just contains a few RST files that re-create the TOC in the full depth you want to have it.

Then you will see whether it has anything to do with Jupyter notebooks or `nbsphinx`.

And if not, you can create an issue on https://github.com/readthedocs/sphinx_rtd_theme.

And if it turns out to be caused by `nbsphinx`, we can continue here.

**Comment by datalifenyc** [comment]
After some further digging and adjusting the headers in jupyter notebook to see the results, I stumbled upon a sphinx_rtd_theme discussion with the same issue:

[Left sidebar context lost when subheading link clicked #290 ](https://github.com/readthedocs/sphinx_rtd_theme/issues/290)

@magopian explains that the header link generated by sphinx isn't recognized by the toctree.

I will close this issue since it is not a nbsphinx issue. [I'm not sure if this is adjustable within nbsphinx.] 

Thank you for your assistance in walking me through the various paths to check in troubleshooting this issue.

**Comment by mgeier** [comment]
I'm not sure if that's the same issue.
And that issue is said to be fixed, so why would it still be affecting you?

At least I know now that you are talking about "section links", right?
You are talking about clicking on those little symbols next to the section titles, right?

I'm also not sure whether or not `nbsphinx` has anything to do with the problem.
The issue you mentioned has something to do with header links, and `nbsphinx` *does* change the header links compared to "normal" RST files, so it might well be the culprit.

But I don't know as long as you don't try it without `nbsphinx` and see whether the problem persists or not.

Did you try the `master` branch of `sphinx_rtd_theme`?
