### ISSUE TITLE
struggling with images

### ISSUE THREAD

**Issue by parmentelat** [spatialaudio/nbsphinx#437]
as per your request in https://github.com/chrisjsewell/ipypublish/issues/133

I have given a try to nbsphinx to convert towards readthedocs.io a set of slideshow notebooks
those slides contain images that come in a variety of ways

* as often as possible, using pure markdown `![](pictures/image.png)`
* sometimes as a html tag when I need to resize `<img src="pictures/image.png" height="400px">`
* and even sometimes as more elaborate html tags, when I want to have them float on the right or left hand side of the page; this last usage is admittedly quite rare

in any case it looks like all the instances where I used the 2nd approach just vanish from the final html result after I run sphinx; this is a pain because there are a lot of the pictures, and I don't feel comfy with messing with them all, b/c because it would jeopardize the slideshow rendering, which is its first, and until now foremost, purpose :)

**Comment by mgeier** [comment]
Thanks for the report!

It is known behavior that `<img>` tags don't survive the conversion (and their `src` files are not copied to the HTML directory).

Support for `<img>` tags has been requested quite a few times already:

#52
#284
#321

I've said in https://github.com/spatialaudio/nbsphinx/issues/284#issuecomment-603391556 that I'm not planning to work on this, but probably I should finally implement it (since nobody else seems to volunteer)?

**Comment by mgeier** [comment]
OK, I've given it a try ...

Sadly, I couldn't make the `align` attribute work, but specifying the size should work with #438.

**Comment by mgeier** [comment]
I've just made a new `nbsphinx` release (0.7.0) which includes the `<img>` parsing feature.

As mentioned above, the `align` attribute is not supported, but you can assign a `class` and then handle the alignment with [custom CSS](https://nbsphinx.readthedocs.io/en/0.7.0/custom-css.html).

@parmentelat Does that work for you?

**Comment by mgeier** [comment]
I guess this can be closed.
