### ISSUE TITLE
Question: consistent highlighting for rst / markdown code blocks

### ISSUE THREAD

**Issue by tshead2** [spatialaudio/nbsphinx#447]
I have a notebook containing a mixture of code cells, markdown cells containing code:

    ```
    # my code here
    ```

and raw rst cells containing code blocks:

     .. code-block::
    
        # my code here

However, the syntax highlighting for the markdown and raw rst does not match the highlighting for the notebook code cells.  Is there a trick to make them the same?  I assume that if I could see the rst generated by nbsphinx, it'd be clear how to make the manual markup match.

Thanks in advance,
Tim

**Comment by mgeier** [comment]
If you want to see the generated RST, you can try out the `save-rst` branch: https://github.com/spatialaudio/nbsphinx/tree/save-rst.

You can use `highlight_language` to choose the default highlight language: https://nbsphinx.readthedocs.io/en/0.6.1/usage.html#highlight_language.

And in your code blocks, you can specify the language for each instance:

````
```python
# my code here
```
````

```
.. code-block:: python

   # my code here
```

Does that help?

If not, can you please provide screenshots?

**Comment by tshead2** [comment]
Thanks for the quick response.  I've tried many different permutations with-and-without the highlight directive, with-and-without explicitly specifying the language, and-so-on, but I always get the following:

<img width="935" alt="image" src="https://user-images.githubusercontent.com/4997768/80508915-e4049900-8935-11ea-9d7c-718897699672.png">

The first (greenish) block of code comes from a `code-block` directive in a raw RST cell, while the second block is a regular code cell in the source notebook.  This is a local build of the documentation using the _sphinx_rtd_theme_ to match the appearance when it's deployed to readthedocs.io, in case that matters.

Cheers,
Tim

**Comment by mgeier** [comment]
I can't reproduce the problem. I never get those greenish blocks.

Can you please provide a minimal example project?

My code blocks always look like those on the page https://nbsphinx.readthedocs.io/en/0.6.1/a-normal-rst-file.html. They look the same as this one: https://nbsphinx.readthedocs.io/en/0.6.1/markdown-cells.html#Code.

**Comment by tshead2** [comment]
Well, my minimal example (created from scratch, following https://nbsphinx.readthedocs.io/en/0.6.1/usage.html) works correctly, so it must be something in the configuration at my end.  Think I'll copy the minimal conf.py over to my real project, and gradually reintroduce changes until the problem resurfaces.  Apologies for the wild goose chase.

**Comment by mgeier** [comment]
OK, I found the culprit: [pygments_style](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=pygments_style#confval-pygments_style).

The `sphinx_rtd_theme` uses the Pygments style `'default'` by default (which has a grey background), but I think `sphinx-quickstart` uses

```python
pygments_style = 'sphinx'
```

... which has this sickly greenish background.

I never thought about this, but while the Pygments *language* can be chosen with [nbsphinx_codecell_lexer](https://nbsphinx.readthedocs.io/en/0.6.1/usage.html#nbsphinx_codecell_lexer), the Pygments *style* cannot be chosen (and AFAIK, `nbsphinx` doesn't make an explicit choice, either).
Probably we should add an option for that?

**Comment by tshead2** [comment]
I'm just happy to have consistent results now, I'm not that picky about the style.

Cheers,
Tim

**Comment by DominiqueMakowski** [comment]
Hey, I am having a similar issue, in the sense that I'd like the code chunks to be black in my documentation. Hence I set `pygments_style = 'monokai'`. 

While this works great for RST code chunks, for the converted Jupyter notebooks it only colours the text, but not the background colour. As a result, it's unreadable as it's basically white text on white background...

Is there a way to also change the background colour of jupyter notebooks so that it follows the style set as `pygments_style`? Thanks a lot ☺️

**Comment by mgeier** [comment]
> Is there a way to also change the background colour of jupyter notebooks so that it follows the style set as `pygments_style`?

I don't know, probably you can do it by overriding some CSS styles?

Currently, `nbsphinx` tries to remove the background color from the theme, which apparently also affects the background color from Pygments:

https://github.com/spatialaudio/nbsphinx/blob/15742f04e7562a04f036f777072ae88c14546aa6/src/nbsphinx.py#L427-L443

After that, it sets the background color of the input area of code cells:

https://github.com/spatialaudio/nbsphinx/blob/15742f04e7562a04f036f777072ae88c14546aa6/src/nbsphinx.py#L539-L544

The idea was to make it look similar to the way it looks in Jupyter.

But probably we can improve this somehow?

@DominiqueMakowski What `html_theme` are you using?
What is the background color of the main text?
Could you please provide a screenshot (or mock-up) of how you would like it to look ideally?

**Comment by DominiqueMakowski** [comment]
The documentation in question can be found [here](https://neurokit2.readthedocs.io/en/latest/introduction.html) and the conf.py file [here](https://github.com/neuropsychology/NeuroKit/blob/master/docs/conf.py).

The HTML theme is `html_theme = 'sphinx_rtd_theme'`.

Regarding the goal, here's a current code chunk from an RST file (..code directive):

![image](https://user-images.githubusercontent.com/8875533/81474288-fd132100-9236-11ea-96f8-d2f9241876ef.png)


And here's from a converted notebook:

![image](https://user-images.githubusercontent.com/8875533/81474293-11efb480-9237-11ea-8ca8-c5470686c82d.png)


However, if I set `pygments_style = 'monokai'` in the conf file (instead of "default"), this is my RST code chunk:


And this is a code chunk from the converted notebook:


I would like the last one to be the same as the above one, i.e., unified (the syntax is already highlighted similarly, it's just the background color set by pygments that is not taken into account during the conversion it seems).

**Comment by mgeier** [comment]
The problem is that the input and output areas of code cells look different in Jupyter.
And I think it would be good to keep that distinction.

I think I know how you want the *input area* to look like.
But how should the *output area* look like?
Please provide an example with "plain text" output (as opposed to, e.g. a plot).

**Comment by DominiqueMakowski** [comment]
Thats a good point! 

> And I think it would be good to keep that distinction.

Agree, here's how it look correctly:

![image](https://user-images.githubusercontent.com/8875533/81476845-b7f6eb00-9246-11ea-8382-f4da7316cd45.png)


I have no strong preference for the output area, I think as default (as it is now) is okay 👌 as it as you say clearly separate the input from output

**Comment by mgeier** [comment]
I've created an experimental PR: #463.

Can you please try it out?

**Comment by DominiqueMakowski** [comment]
Thanks! since I rely on readthedocs to build the doc, may I know how I can specify to use a particular PR?

**Comment by mgeier** [comment]
You should really try to run Sphinx locally, this makes for much faster trial/error iterations. See [CONTRIBUTING.rst](../blob/master/CONTRIBUTING.rst) for how to make a development installation.

But of course you can also use a branch on RTD, see https://nbsphinx.readthedocs.io/en/0.7.0/usage.html#Using-requirements.txt. In the case of #463, you can use this in your `requirements.txt`:

    git+https://github.com/mgeier/nbsphinx.git@pygments-background

**Comment by DominiqueMakowski** [comment]
Thanks for your help, with @Tam-Pham help we built the docs locally using this PR, but it doesn't seem to solve the issue: changing pygments style still affects the nb blocks partially (i.e., without the background that remains light). 

Related to the reservation that you had regarding how changing this would result in some users having the greenish background, I'd say another possibility is to fix the syntax highlight not to be affected by the `pygments_style` argument. This would maintain coherence at the expense of consistency in the documentation. 

(Although I'm personally not sure it's the best route, as I do believe that users expect the highlighting style to be consistent and unified across their documentation, regardless of whether it is an RST or a converted notebook.)

**Comment by mgeier** [comment]
> changing pygments style still affects the nb blocks partially (i.e., without the background that remains light).

What theme were you using?

As mentioned in #463, most themes override the background.

It would probably help if you could provide a minimal example project. Then I could try if I can reproduce the problem.

> Related to the reservation that you had regarding how changing this would result in some users having the greenish background, I'd say another possibility is to fix the syntax highlight not to be affected by the `pygments_style` argument.

I don't understand, can you please elaborate?

> (Although I'm personally not sure it's the best route, as I do believe that users expect the highlighting style to be consistent and unified across their documentation, regardless of whether it is an RST or a converted notebook.)

Note that notebooks can also have code blocks in Markdown cells.
I agree that it makes most sense if those code blocks look like the code blocks in RST pages.

However, code cells are different than code blocks in Markdown cells, so I don't see a logical problem if they look different.

**Comment by DominiqueMakowski** [comment]
> What theme were you using?

I am using 'monokai' (a dark theme).

> I don't understand, can you please elaborate?

Currently, the problem exists because the `pygments_style` argument of sphinx affects notebook code cells in a partial way, i.e., it changes the highlight color of the text, but not the background. This results in problems when using dark themes which text is usually white: as the background is fixed to be white in the nb code cells, and the text turns to white as well, it becomes unreadable.

I think there are two possible satisfactory ways of solving of this puzzle:

- Semi-unification: RST code blocks + code blocks from markdown cells look the same, and keep the code cells different. For this, it is required to prevent the code cells to been affected by `pygments_style`, so that their style remains fixed (but readable) no matter what the users puts in the pygents_style argument. 
- Full-unification: all code chunks (RST code blocks, code blocks from markdown and code cells) look the same. For this, the "fixation" of the background color of code cells must be lifted to allow it to follow the theme defined in `pygments_style`.

While both are satisfactory and *logical* to some extent, I think users implicitly expect code chunks to look the same, independently of their source or type, therefore my personal preference goes to the second option, but that's ultimately your call ☺️ 

 > It would probably help if you could provide a minimal example project. Then I could try if I can reproduce the problem.

I can try, but unfortunately my skills in sphinx, and setuping a python project are very very rusty. Do you know of any template that I could fork that could provide me with an example project. That being said, the only thing to reproduce is to set `pygments_style='monokai'` in the conf.py file.

**Comment by mgeier** [comment]
> > What theme were you using?
> 
> I am using 'monokai' (a dark theme).

Sorry, I wasn't clear, I meant "HTML theme", i.e. `html_theme`.

If you would provide a minimal example, I wouldn't have to guess your setup.

> Semi-unification: RST code blocks + code blocks from markdown cells look the same, and keep the code cells different. For this, it is required to prevent the code cells to been affected by `pygments_style`, so that their style remains fixed (but readable) no matter what the users puts in the pygents_style argument.

OK, I see.
I guess this would be a possibility.
I'll have to check whether this could be implemented in a reasonable way.

> Full-unification: all code chunks (RST code blocks, code blocks from markdown and code cells) look the same. For this, the "fixation" of the background color of code cells must be lifted to allow it to follow the theme defined in `pygments_style`.

Yes, that's what I did in #463, but the problem there is that it only works with a subset of HTML themes (which might be OK?).

> While both are satisfactory and _logical_ to some extent, I think users implicitly expect code chunks to look the same, independently of their source or type

I'm not sure if that's true. Code chunks already look different in JupyterLab, the Classic Notebook and `nbviewer` (and probably others):

* code blocks in Markdown cells have no background (or white background?) and no border
* the input area of code cells have a light grey background and a thin border

> > It would probably help if you could provide a minimal example project. Then I could try if I can reproduce the problem.
> 
> I can try, but unfortunately my skills in sphinx, and setuping a python project are very very rusty. 

I'm not sure what you mean by a "python project", but creating a Sphinx project is simple: https://nbsphinx.readthedocs.io/en/0.7.0/usage.html#Sphinx-Setup

> Do you know of any template that I could fork that could provide me with an example project.

I'm not a fan of templates because I think they lead to cargo-cult programming.

For a minimal example you need exactly two files:

* a notebook called `index.ipynb`
* a file called `conf.py` containing `extensions = ['nbsphinx']`

... and you need to know a single command:

    python3 -m sphinx . _build

That's it. No need to fork anything.

> That being said, the only thing to reproduce is to set `pygments_style='monokai'` in the conf.py file.

It's also quite important what `html_theme` setting you use.
And I don't know, maybe other settings are relevant as well?
It would have definitely saved me a significant amount of time working on this issue if it had had a minimal example project from the beginning.

Don't get me wrong, though. I *like* responding to issues and helping people. Otherwise I simply wouldn't do it.

**Comment by DominiqueMakowski** [comment]
Apologies for the miscommunication, and thanks for trying to help nonetheless! as I mentioned above, you can find [here](https://github.com/neuropsychology/NeuroKit/tree/dev) the project that I am referring to, including his [conf.py](https://github.com/neuropsychology/NeuroKit/blob/dev/docs/conf.py#L142) which has `html_theme = 'sphinx_rtd_theme'` set.

I rarely build the docs locally as we are covered by an awesome beta readthedocs feature that checks and builds the documentation at each new commit ([see here](https://neurokit2--209.org.readthedocs.build/en/209/)), and since I tend to make a lot of small commits, I rely on it to save time, rather than on local builds.

> I'm not a fan of templates because I think they lead to cargo-cult programming.

Thanks for that, I just discovered this concept :)

**Comment by mgeier** [comment]
Thanks for the additional info, but I still don't know what's going on.

You are saying (in https://github.com/spatialaudio/nbsphinx/issues/447#issuecomment-628545282) that #463 is not working for you (when you compile locally), but *if* you use `sphinx_rtd_theme` and `monokai`, it should work. At least it does for me.

A minimal example would very likely shed some light on this.

> we are covered by an awesome beta readthedocs feature that checks and builds the documentation at each new commit ([see here](https://neurokit2--209.org.readthedocs.build/en/209/))

Yes, that's a great feature, I'm also using it with `nbsphinx`.
It's still useful to create the docs locally while working on some details that needs quick iterations.

Your example, BTW, doesn't seem to use the `monokai` style, nor does it seem to use #463, right?

**Comment by DominiqueMakowski** [comment]
![WhatsApp Image 2020-05-16 at 19 43 35](https://user-images.githubusercontent.com/8875533/82119045-d82a2b00-97ad-11ea-8a46-140f66d46793.jpeg)

Apologies, in fact we made a mistake in using the PR branch. We have updated it and it seems to work as expected ☺️ ([example](https://neurokit2--209.org.readthedocs.build/en/209/examples/ecg_delineate.html))

Thanks a lot for your patience and help! I hope that you will consider keeping this unified style for code blocks in the main version :)

**Comment by mgeier** [comment]
OK, that's what I thought.

> I hope that you will consider keeping this unified style for code blocks in the main version

I'm still undecided about that, but I think there are some good arguments for merging #463.
There are also a few open questions.

You could help me move this along by commenting on https://github.com/spatialaudio/nbsphinx/pull/463#issuecomment-630761141 and by finding a solution to the problem described in https://github.com/spatialaudio/nbsphinx/pull/463#issuecomment-630762877.

BTW, off topic, regarding your code example above:
The line `%matplotlib inline` isn't needed anymore in modern IPython versions, because it became the default some time ago.
And regarding the figure size (which you are probably unnecessarily increasing), please see my little pamphlet about the default values of the `inline` backend: https://nbviewer.jupyter.org/github/mgeier/python-audio/blob/master/plotting/matplotlib-inline-defaults.ipynb.

**Comment by DominiqueMakowski** [comment]
> BTW, off topic, regarding your code example above:

Thanks for catching that!

I'll try to help to the best of my abilities
