### ISSUE TITLE
AttributeError: 'Sphinx' object has no attribute 'add_source_suffix'

### ISSUE THREAD

**Issue by schymans** [spatialaudio/nbsphinx#449]
I installed nbsphinx in my conda environment but as soon as I add 'nbsphinx' to my conf.py, `make html` fails with:
```
Exception occurred:
  File "/home/user1/Programs/miniconda3/envs/essm-master-py3/lib/python3.7/site-packages/nbsphinx.py", line 2108, in setup
    app.add_source_suffix('.ipynb', 'jupyter_notebook')
AttributeError: 'Sphinx' object has no attribute 'add_source_suffix'
```
Any clues what might be going wrong?

**Comment by mgeier** [comment]
You seem to be using a Sphinx version below 1.8, right?

`nbsphinx` needs at least version 1.8 (because that's when the mentioned function was introduced: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_source_suffix), see:

https://github.com/spatialaudio/nbsphinx/blob/93398b9d8ba3922e860486d7eacf9eeb3b036580/setup.py#L16-L23

How did you install `nbsphinx`?

If you were using conda-forge, you should probably report this at https://github.com/conda-forge/nbsphinx-feedstock

**Comment by schymans** [comment]
Wow, thanks for the quick feedback! I had not seen that I used the wrong sphinx version. Now it works after I created a new conda environment and ran `pip install sphinx==1.8` and `pip install nbsphinx`.

**Comment by mgeier** [comment]
So you initially installed `nbsphinx` with `conda` (probably via an environment) from the `conda-forge` channel, right?

You shouldn't have to worry which version of Sphinx to install, this should be taken care of by `conda`. But it isn't, so I created a bug report: https://github.com/conda-forge/nbsphinx-feedstock/issues/24.

In the meantime, you probably shouldn't use `==` to specify the version. If you use `sphinx>=1.8`, you'll get the latest Sphinx version.

**Comment by schymans** [comment]
Thanks, but unfortunately, a whole lot of stuff changed in the later versions of sphinx, so version 1.8 was the one that required only minimal changes to my project while allowing to use nbsphinx.
I had a mess in my conda environment, as I had installed all the requirements for my project using pip, and it actually had sphinx<1.8 stated in there due to its conf.py. So I am not sure it is actually a bug in conda. Thanks anyway!

**Comment by mgeier** [comment]
OK, thanks for the update.

So I guess we can close this issue?

**Comment by schymans** [comment]
Yes, sorry!
