### ISSUE TITLE
Invalid reStructuredText for markdown cell with image followed by cell with leading block quote

### ISSUE THREAD

**Issue by huonw** [spatialaudio/nbsphinx#450]
If a notebook has consecutive markdown cells like:

1. one contains an image or any other structure that results in a reStructuredText (rST) directive at the end of the rST for that cell, including raw HTML like `<table></table>`
2. one that starts with a block quote `> ...`

Then the resulting rST is invalid, because the block quote text gets included with the content of the directive, since it's only marked via indentation (https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#block-quotes).

Reproducer: https://github.com/huonw/nbsphinx-consecutive-cell-reproducer 
- Clone that repo
- Open `_build/html/image_quote_more.html` (or view it without styling at <https://htmlpreview.github.io/?https://github.com/huonw/nbsphinx-consecutive-cell-reproducer/blob/master/_build/html/image_quote_more.html> )
- Compare it to the original notebook in the top level `image_quote_more.ipynb`: https://github.com/huonw/nbsphinx-consecutive-cell-reproducer/blob/master/image_quote_more.ipynb

Notably:

- the first image shows the wrong image (it should be the jupyter logo, not the jupyter hub one)
- the first quote disappears
- the second quote is formatted as raw HTML
- when everything is in a single cell, it all works correctly

See https://github.com/huonw/nbsphinx-consecutive-cell-reproducer/commit/6ea5829191d279c2488a17f1329f54e8e650ecec for exactly what was added over the raw `sphinx-quickstart` output (specifically, I ran `sphinx-quickstart -q -p test -a test -r 1.0.0 -l en`).

Sphinx version: 3.0.3
Nbsphinx version: 0.6.1

This is the same issue as https://github.com/jupyter/nbconvert/issues/1245 which explores the underlying rST in more detail. I'm filing it here too because, AIUI, nbsphinx has its own conversion pipeline.

(Thanks for nbsphinx! It's working really well other than this edge case :+1: )

**Comment by mgeier** [comment]
Thanks for the report and thanks for the nice "reproducer"!

The good news is that this causes a warning, so when you use Sphinx's `-W` option, you'll clearly see that something is wrong.

I've already fixed a few similar bugs in the past, e.g.:

https://github.com/spatialaudio/nbsphinx/blob/c0dfb11584d5935212260af4b2d742b3c10bd3f7/src/nbsphinx.py#L255-L256

... but apparently I didn't fix everything ...

I just created #451 which should fix the problem.
If you discover further edge cases, please let me know!

> the first image shows the wrong image (it should be the jupyter logo, not the jupyter hub one)

That's a separate issue (#162), which is really a Pandoc issue (https://github.com/jgm/pandoc/issues/6194), which should be fixed in Pandoc's `master` branch, but there hasn't been a new release since.

> AIUI, nbsphinx has its own conversion pipeline.

It has, but it currently still inherits the RST template from `nbconvert` but I'm not sure if a fix there would also fix it here.
