### ISSUE TITLE
Only read .doc.ipynb, ignore all other *.ipynb files

### ISSUE THREAD

**Issue by klieret** [spatialaudio/nbsphinx#462]
## What I want

I want to avoid having sphinx read/convert/execute all ``.ipynb`` files of a larger repository. Only ``.doc.ipynb`` files should be converted.

## Why I can't get it to work

Unfortunately this doesn't seem to be possible, because ``.ipynb`` is always added to the ``source_suffix``es and to the ``nbsphinx_custom_formats`` and excluding ``.ipynb`` via ``exclude_patterns`` also excludes ``.doc.ipynb``. 

This could be easily avoided by using ``ipynb_doc`` as my extension, but then Jupyter won't recognize the file format anymore.

Is there any way to achieve this?

**Comment by mgeier** [comment]
Yes, the `.ipynb` suffix is added quite aggressively and non-configurably. But I think that's actually OK.

The problem here is really that the `exclude_patterns` syntax isn't powerful enough to ignore exactly the files you want to be ignored.

The simplest solution would be to to separate your notebooks into different directories. Those are easy to ignore.

Another simple solution would be to give a special name to all your non-doc notebooks.

But I think you might also be able to make it work with your current naming scheme.
You can try to tune your pattern a bit. I don't think it's possible to get exactly the behavior you are describing, but I think you can get very close, and it might well be sufficient for your case:

```python
exclude_patterns = ['**[!.]???.ipynb']
```

This should ignore all the notebooks that don't have a dot at the right spot, but it doesn't matter which three letters follow that dot.

So if you want to ignore files like `test-something.tst.ipynb` or `strange.wtf.ipynb`, this pattern won't work for you. Do you have such files?

I also tried a sequence of multiple negated characters (`'**[!.][!d][!o][!c].ipynb'`), but this didn't seem to work as I expected.

**Comment by klieret** [comment]
Hi @mgeier. Thanks for taking your time to answer so thoroughly.

I do appreciate your workaround solutions, but none of them make me completely happy. It's for a repository with a lot of active users, so asking everyone to rename their files to exclude them, or having the regular expression produce surprising matches (``strange.wtf.ipynb``) is a bit unsatisfactory.

However, I agree that this is ultimately a shortcoming with ``exclude_patterns``, which doesn't accept extended regular expressions (else we could use ``**/*(!.doc).ipynb`` or similar). 

I might look through the sphinx code to see if that can be enhanced.

While I would be happy for a ``nbsphinx`` switch to not automatically include the ``.ipynb`` suffix, I also understand if you do not want to introduce more complexity. 
Still, I think that this is a problem that more people who are collaborating in one big repository will run into, so perhaps it would be worth it.

**Comment by mgeier** [comment]
> but none of them make me completely happy

I know.

> having the regular expression produce surprising matches (`strange.wtf.ipynb`) is a bit unsatisfactory.

Granted, but ...

* the chances of that ever actually happening are pretty slim
* the repercussions are fairly mild
  * a Sphinx warning
  * some waste of computing power and probably human time
* the fix is super easy, barely an inconvenience
  * just add a new pattern to `exclude_patterns`

Given all that, I don't think this would warrant a major implementation effort in `nbsphinx`.

Having said that, if you have ideas how to improve the situation (probably with advantages beyond this issue), I'd be happy to hear them!

> Still, I think that this is a problem that more people who are collaborating in one big repository will run into

If that's actually true, I'd like to hear from them.

AFAIU, the problem only appears if you have ...

* two sets of Jupyter notebooks
  * one for the docs
  * one for something else
  * they cannot be in separate directories

I'm especially wondering about the last point: why would it be so disadvantageous to put those two sets of notebooks into separate places?

**Comment by klieret** [comment]
> I'm especially wondering about the last point: why would it be so disadvantageous to put those two sets of notebooks into separate places?

Not disadvantageous at all, it's just one more thing that needs to be communicated and kept in mind. 

> Given all that, I don't think this would warrant a major implementation effort in nbsphinx.

Yes, I totally understand that. Thank you for thinking this through and giving your frank opinion. Let me close this issue.
