### ISSUE TITLE
unresponsive height / distorted prompt outputs

### ISSUE THREAD

**Issue by VolkerBergen** [spatialaudio/nbsphinx#464]
Dear @mgeier,

this package is amazing and has been very handy in auto-converting my notebooks. 

Until version 0.3.5, prompt output figures had a fixed shape. After 0.4.0 it got a responsive width. However, the height is yet unresponsive, such that my figures [here](https://scvelo-notebooks.readthedocs.io/DynamicalModeling.html) get quite distorted once they don't fit to the screen width anymore.

Would very much appreciate any help on that.

Best
Volker

**Comment by mgeier** [comment]
I don't quite know what you mean, can you please clarify?

Probably some screenshots would help?

**Comment by VolkerBergen** [comment]
Thanks for the quick response. The documentation is hosted [here](https://scvelo-notebooks.readthedocs.io/DynamicalModeling.html). On the full-screen browser the converted notebook is displayed correctly [here](https://user-images.githubusercontent.com/31883718/81793690-0556af00-950a-11ea-9018-e0d9635f0072.png), while on a smaller screen or mobile it looks like this:
![image](https://user-images.githubusercontent.com/31883718/81793868-39ca6b00-950a-11ea-9a57-edb34e2872cc.png). 

Widths of images change dynamically with screen size, while heights stay fixed.

**Comment by VolkerBergen** [comment]
Was spending quite some time trying to figure out how to fix that, unsuccessfully. It works perfectly with thumbnail galleries. So that should be easily solvable, I just can't figure out how.

**Comment by mgeier** [comment]
Thanks for the screenshot, now I know what's going on!

The problem occurs when the images in code cell outputs have width and height metadata.

For example, this happens when using `png2x`/`retina` as print option.
The `nbsphinx` docs show the same problem in the last plot example: https://nbsphinx.readthedocs.io/en/0.7.0/code-cells.html#Plots.

One work-around would be to avoid this metadata, e.g. by using SVG plots.

The problem can be easily reproduced in a RST file, without the involvement of `nbsphinx`:

```rst
.. image:: https://www.python.org/static/img/python-logo-large.png
   :width: 844
   :height: 1048
```

I think this is actually a bug in the Sphinx HTML theme.

I don't know what a reasonable solution would be, any ideas?

**Comment by VolkerBergen** [comment]
Awesome, running with `svg` solves it! Thanks, should have asked you before spending hours on this.

**Comment by VolkerBergen** [comment]
`svg` is not satisfactory, unfortunately, because the html page loads very slowly.
Do you know of any possibility to remove the metadata? And do you have any clue, why it used to work perfectly with nbsphinx v0.3.5 (which is the only version where it adjusted png's correctly).

**Comment by mgeier** [comment]
> `svg` is not satisfactory, unfortunately, because the html page loads very slowly.

You could try using the "rasterization" feature of Matplotlib: https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.artist.Artist.set_rasterized.html

I'm not sure if this would work in your case (and if it would look nice), but it might reduce the size of the SVG.

> Do you know of any other possibility to remove the metadata?

The metadata is there for a reason, you shouldn't simply remove it.

But, as you noticed, using `png` instead of `png2x` doesn't need re-scaling the images, so no metadata is necessary in that case.

There is another option, though: you could try to fix the HTML theme by using some custom CSS (https://nbsphinx.readthedocs.io/en/0.7.0/custom-css.html):

```css
img {
    max-width: unset;
}
```

> And do you have any clue, why it used to work perfectly with nbsphinx v0.3.5 (which is the only version where it adjusted png's correctly).

I doubt it worked "correctly" or "perfectly" with version 0.3.5.

I guess the figures were displayed in their "native" size instead of the intended size given by the metadata. Which was wrong.

I fixed this in 274e68b4595a0748beda5100594b03ddc69298b7.

If you think it's still not right, please let me know!

**Comment by VolkerBergen** [comment]
Really appreciate your detailed comment on this. Rasterization didn't help, neither did custom_css. However, using `png` works totally fine for me. Thanks a lot for you help!

**Comment by mgeier** [comment]
It's great that `png` works for you.

I'm still curious why the CSS solution didn't work, can you please explain?
I'm working on my own Sphinx theme and I'd like to avoid the problem there.

**Comment by michalk8** [comment]
@mgeier @VolkerBergen 
The CSS solution worked for me, after some modifications - using `png2x` is therefore possible:

```css
.rst-content .image-reference img {
   max-width: unset;
   width: 100% !important;
   height: auto !important;
```
