### ISSUE TITLE
Correct gallery styles locally, but not on RTD

### ISSUE THREAD

**Issue by tshead** [spatialaudio/nbsphinx#523]
Creating a gallery works fine locally, but the appearance is off when deployed to readthedocs, see https://imagecat.readthedocs.io/en/latest/gallery.html to see what I mean - the image thumbnail sizes are much larger than for the local build.

My conf.py includes

```
extensions = [
    "nbsphinx”,
    "sphinx_gallery.load_style”,
    ...
]
```

and requirements.txt includes

```
nbsphinx
sphinx-gallery
...
```

Is there something else I need to add to get it working?  It looks to me like the readthedocs deployment is missing the CSS styles for the gallery, am I supposed to add them manually to the configuration somewhere?

Thanks in advance,
Tim

**Comment by mgeier** [comment]
> Is there something else I need to add to get it working?

No, that should be it.

> am I supposed to add them manually to the configuration somewhere?

Nope, that's what `sphinx_gallery.load_style` is supposed to do.

This normally causes `gallery.css` to be included in your HTML file, see for example the HTML source of https://nbsphinx.readthedocs.io/en/0.8.0/subdir/gallery.html.

In you example, that's not the case.

I guess this is because you are manipulating the `html_context` (https://github.com/shead-custom-design/imagecat/blob/7f445a4a0886b172138ff53b18d2f427b772022b/docs/conf.py#L86-L91), which is *not* the proper way to add CSS files.

The proper way is to use `html_css_files`, see https://nbsphinx.readthedocs.io/en/0.8.0/custom-css.html#For-All-Pageshtml_css_files.

**Comment by tshead** [comment]
@mgeier - hmm, that block of code came from the original install instructions for the RTD theme.  I see now that those instructions have changed *a lot*; cleaning-up conf.py and using the up-to-date instructions solves the problem.  Sorry to bug you.

Many thanks,
Tim
