### ISSUE TITLE
toctree lists header level information lost/mixed up.

### ISSUE THREAD

**Issue by elkeschaper** [spatialaudio/nbsphinx#55]
Hi all,

first, congrats to a great project! Very useful!

I've noticed that the header level information from the _.ipynb_ files are not consistently transferred to _.html_.

E.g. this the result of running `python3 setup.py build_sphinx` locally on a clone of this library `https://github.com/spatialaudio/nbsphinx`:
![a](https://cloud.githubusercontent.com/assets/5979427/16387909/28b47c7c-3c97-11e6-9bea-12ea9710fc93.png)

And this is what it should like (please only look at the structure):
![b](https://cloud.githubusercontent.com/assets/5979427/16387912/2ea1e48a-3c97-11e6-8767-c7f1f65fac9b.png)

Do you see how the levels were changed? I noticed this bug for the first time on my own project, so it seems to be consistent on my system (Python 3.5.0):

`
docutils==0.12
ipdb==0.8.1
ipykernel==4.3.1
ipython==4.2.0
ipython-genutils==0.1.0
ipywidgets==5.1.5
jupyter==1.0.0
jupyter-client==4.3.0
jupyter-console==4.1.1
jupyter-core==4.1.0
nbconvert commit q64aeeefa872be8c8885437b20fa1f0f6c45b8d58
pypandoc==1.1.3
Sphinx==1.4.2
sphinx-bootstrap-theme==0.4.9
sphinx-rtd-theme==0.1.9
`

Thanks for any ideas!

**Comment by mgeier** [comment]
This is indeed very strange!

For me, the heading levels have always worked, both locally and online on RTD.

Does this occur only with nbsphinx or also with "pure" (only using RST files) Sphinx projects?

I have no clue what's causing this, but as a first step I'd probably try to install the minimum amount of packages in a virtualenv and see if the error still occurs.

It might also have something to do with pandoc, because it's used to process the Markdown cells, I'm currently using version 1.16.0.2.
You could probably try to run only the content of a single Markdown cell (that shows the error) through your local pandoc ...

I that leads nowhere, you can also try to have a look at the internal RST representation, see https://github.com/spatialaudio/nbsphinx/issues/22#issuecomment-188702787.

**Comment by elkeschaper** [comment]
Thanks for the ideas!

The problem when running `python3 setup.py build_sphinx` still persists (on Mac OSX) with 

 - pandoc updated to 1.17.1 (Compiled with texmath 0.8.6.3, highlighting-kate 0.6.2.)
 - on a fresh virtualenv (Python 3.5.0) with these installations:
```
 pip install git+https://github.com/spatialaudio/nbsphinx
 pip install sphinx_bootstrap_theme
 pip install jupyter-client
```
[btw, jupyter-client seems to be needed for the nbsphinx package, but not automatically installed with pip ?]

such that pip freeze results in:
````
alabaster==0.7.8
Babel==2.3.4
decorator==4.0.10
docutils==0.12
entrypoints==0.2.2
imagesize==0.7.1
ipython-genutils==0.1.0
Jinja2==2.8
jsonschema==2.5.1
jupyter-client==4.3.0
jupyter-core==4.1.0
MarkupSafe==0.23
mistune==0.7.2
nbconvert==4.2.0
nbformat==4.0.1
nbsphinx==0.2.8
Pygments==2.1.3
pytz==2016.4
pyzmq==15.2.0
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.4
sphinx-bootstrap-theme==0.4.9
traitlets==4.2.1
```


On the other hand, this problem does not occur in a pure .rst setting, nor does it impair the header structure of toctreed .rst files in a .rst/.ipynb mix setting.


So I'm not sure what to try anymore...

**Comment by elkeschaper** [comment]
Update: I believe I might have found a fix (though not obvious):
If I run a notebook manually (from within jupyter notebook), the header structure seems to transferred alright even to the Sphinx docs.

For example, I've manually run `code-cells.ipynb` and `raw-cells.ipynb`, and the header structure now looks as follows:

![a](https://cloud.githubusercontent.com/assets/5979427/16411860/85957922-3d29-11e6-8530-5d8f4016f963.png)

So, it seems there is a workaround, though this behavior is unexpected?

**Comment by mgeier** [comment]
The behavior is definitely unexpected!

It is *really strange* that executing a notebook with `nbconvert` seems to have an influence on Markdown cells.

Can you try to execute one of the notebooks with `nbconvert`?

    python3 -m nbconvert --to <format> --execute code-cells.ipynb

You can try `html`, `notebook` and probably `pdf` for `<format>`.

You could also try the `save-notebooks` branch, which puts a copy of the *executed* notebook into the HTML output directory.

**Comment by mgeier** [comment]
> jupyter-client seems to be needed for the nbsphinx package, but not automatically installed with pip?

Hmm ... it indeed is needed, but you'll also need a kernel, don't you?
`nbsphinx` doesn't know which kernel you want to use, but any kernel should itself depend on `jupyter-client`, shouldn't it?
Or is that not the case for the non-Python kernels?

How did you install your kernel?

In the example [requirements.txt](https://github.com/spatialaudio/nbsphinx/blob/master/doc/requirements.txt), `ipykernel` is listed, which in turn should require `jupyter-client`, that's why I never realized the missing dependency.

If it is needed anyway, #56 might help?

**Comment by mgeier** [comment]
@elkeschaper Any news? Is it still not working?

**Comment by mgeier** [comment]
Ping @elkeschaper?

I had some problems with the version of `pandoc` installed on RTD, see #69.
Those problems went away when I changed to the version of `pandoc` provided by `conda-forge`.

Probably this also works in your case?

**Comment by loriab** [comment]
No new info here, just confirming that this is still occurring expanding on channel strategies.

I concur that header level information is being lost for files passing through nbsphinx (all ReST files are fine). Also concur that a work-around is to use the conda-forge pandoc. Thus if installing entirely from conda-forge, there's no problem — `conda create -n docenv nbsphinx jupyter_client ipykernel -c source-forge` as one of those automatically pulls in pandoc 1.19 from c-f. If using defaults as primary and c-f as secondary, have to install pandoc explicitly; this gets pandoc 1.15 from defaults and headers go awry. Can get a working build with defaults as primary and c-f as secondary by (at time of writing) forcing channel by version — `conda create -n docenv nbsphinx jupyter_client ipykernel pandoc=1.19 -c defaults -c source-forge`. Below is a working version set.

```
    docutils:         0.12-py35_2    defaults   
    ipykernel:        4.5.2-py35_0   defaults   
    ipython:          5.3.0-py35_0   defaults   
    ipython_genutils: 0.1.0-py35_0   defaults   
    jupyter_client:   5.0.0-py35_0   defaults   
    jupyter_core:     4.3.0-py35_0   defaults   
    nbconvert:        5.1.1-py35_0   defaults   
    nbformat:         4.3.0-py35_0   defaults   
    nbsphinx:         0.2.13-py35_0  conda-forge
    pandoc:           1.19.2-0       conda-forge
    python:           3.5.3-1        defaults   
    sphinx:           1.5.1-py35_0   defaults   
```

**Comment by mgeier** [comment]
Thanks for the update and thanks for confirming that an inappropriate version of `pandoc` is the reason for this strange behavior!

Is there anything that can be added to the docs to help other people not run into the same problem?

**Comment by loriab** [comment]
Most of my nbsphinx docs consulting has been through web searches, and so this was actually the easiest problem to locate and rectify. In retrospect, the [usage](http://nbsphinx.readthedocs.io/en/latest/usage.html) page is pretty clear about the importance of c-f for pandoc, though I suppose it could emphasize c-f for pandoc and nbsphinx together, rather than pip, since the latter is now conda packaged. So no fault toward the docs.

Thanks for a very useful project, [page looks good](http://psicode.org/psi4manual/master/psiapi.html) in the end, and if you should ever need an example of nbsphinx+sphinx-build+CMake+conda-build, let me know.

**Comment by mgeier** [comment]
@loriab I mentioned `conda-forge` (among some other packages) in #103, is this OK?

**Comment by mgeier** [comment]
@loriab I've also made some changes to the CSS in #104 because your info and warning icons were covered by text. Can you please check if this works for you?

**Comment by r9y9** [comment]
I've also run into the same issue. Adding conda-forge channel and installing pandoc 0.19 fixes the problem to me.

**Comment by mgeier** [comment]
I'm closing this because I think in the meantime everyone is using `conda-forge`.

If anybody is still having problems with this, please comment!
