### ISSUE TITLE
Does  `nbgallery` work with `nbsphinx_execute = "never"`

### ISSUE THREAD

**Issue by astrojuanlu** [spatialaudio/nbsphinx#586]
During the SciPy 2021 sprints, we were trying at https://github.com/alan-turing-institute/sktime/pull/1158 to create a gallery of tutorials using `.. nbgallery`. This project has `nbsphinx_execute = "never"` because the notebooks take a lot of time, but the outputs are stored in the notebooks.

However, when running the documentation, the output looks like a `.. toctree` directive with a higher depth:

https://sktime--1158.org.readthedocs.build/en/1158/tutorials.html

![Screenshot 2021-07-17 at 17-15-55 Tutorials — sktime documentation](https://user-images.githubusercontent.com/316517/126041426-3082db4b-dfa0-4a6e-a5a4-7e3535e1af87.png)

We even tried to set the thumbnails explicitly (see https://github.com/alan-turing-institute/sktime/pull/1158/commits/968c8beef9f28050eaf792544f91d1d308c8aa8f).

If we switch `nbsphinx_execute = "always"` and test with only 1 notebook, we get the expected result:

![Screenshot 2021-07-17 at 17-18-17 Tutorials — sktime documentation](https://user-images.githubusercontent.com/316517/126041504-e2c09fbc-94d4-4e11-847a-03ff189abf7c.png)

Is there a way to make the gallery work without executing the notebooks? cc @mloning

**Comment by mgeier** [comment]
Thanks for the report!

This is strange though, because whether or not the notebooks are executed shouldn't have an influence on them being part of a gallery.

I've just tried using `nbsphinx_execute = 'never'` in `nbsphinx`'s own docs, and the galleries are shown as expected, with the missing thumbnails replaced by a generic "broken" thumbnail.
When I pre-execute the notebooks and save them with outputs, it also works as expected.

I think this is something where a minimal reproducible example would help shed light on the problem.

The Sphinx build produces a s***load of warnings (669 to be concrete, see https://readthedocs.org/projects/sktime/builds/14263292/), so I wouldn't be surprised if there is some unexpected behavior. Maybe one of those warnings explains the observed behavior?

**Comment by astrojuanlu** [comment]
Hmmm maybe. So, if the answer is "yes, it should work", let me close this issue and we can investigate more and come with a more specific problem. I agree with you, the number of warnings is just too high.

Thanks @mgeier ! 🙌🏽

**Comment by mloning** [comment]
Thanks @mgeier and @astrojuanlu - yes let's try to sort out our sphinx builds first! 👍

**Comment by mloning** [comment]
Please see https://github.com/alan-turing-institute/sktime/pull/1158#issuecomment-888643385

**Comment by mgeier** [comment]
See #588.
