### ISSUE TITLE
Syntax highlighting doesn't work for Python cells with magic

### ISSUE THREAD

**Issue by marius311** [spatialaudio/nbsphinx#59]
If I have a cell in a Python 3 notebook that says e.g. 

```
%%time
# some python code
```

then when rendered with nbsphinx, the `# some python code` looses its syntax highlighting. Could it be made so that the syntax highlighting is kept, the same way it does in Jupyter notebook itself?

Some info about my setup incase its just a bug:

```
nbsphinx==0.2.9
Sphinx==1.4.6
ipython==5.1.0
jupyter-client==4.3.0
jupyter-core==4.1.1
```

**Comment by mgeier** [comment]
The Jupyter Notebook and `nbconvert` seem to handle that differently. `nbsphinx` is normally closer to `nbconvert`, since it uses a lot of code from there. I think the highlighting in the Jupyter Notebook is done with client-side JavaScript, which cannot be re-used in `nbsphinx`.

I just enabled processing of cell magics in #60. However, the `%%time` magic still has no syntax highlighting, same as in `nbconvert`.

The [`ipython3` lexer](https://github.com/ipython/ipython/blob/master/IPython/lib/lexers.py) seems to disable syntax highlighting when a cell magic is present.

I just saw that this was already reported to `nbconvert` (https://github.com/jupyter/nbconvert/issues/105) and `ipython` (https://github.com/ipython/ipython/issues/9099). Once this is resolved, it should automatically work in `nbsphinx`, too.

**Comment by marius311** [comment]
Thats great, thanks for that. Will wait on the IPython fix then!

**Comment by uweschmitt** [comment]
Any updates here ? Still does not work with `%%file`.

**Comment by mgeier** [comment]
You should ask over there: https://github.com/ipython/ipython/issues/9099

**Comment by mgeier** [comment]
It mostly works now, the missing `%%file` stuff should be fixed in https://github.com/ipython/ipython/pull/11384.

**Comment by mgeier** [comment]
My PR has been merged, so I think this should be fine now.

If there is still some highlighting missing, please leave a comment!

**Comment by jeertmans** [comment]
Hello @mgeier, I'm commenting this because I have the same issue, on a custom magic.

The syntax highlighting within the Jupyter document works fine:

![image](https://github.com/spatialaudio/nbsphinx/assets/27275099/8b0f16fe-d2e5-44e3-8f8c-a4b361f90120)


But, when renderer using `nbsphinx`, it does not work:

![image](https://github.com/spatialaudio/nbsphinx/assets/27275099/bb7fb095-958c-4679-b734-cb8533be2ef1)

Any idea on how to fix that?

**Comment by mgeier** [comment]
What does `nbconvert` do?

See https://github.com/spatialaudio/nbsphinx/issues/59#issuecomment-243383017.

**Comment by jeertmans** [comment]
@mgeier `nbconvert` also fails: should I report that to them?

(Within the notebook viewer)

![image](https://github.com/spatialaudio/nbsphinx/assets/27275099/7f7d748e-944c-49cf-9ad5-b929c01b4570)


(When exported as HTML)

![image](https://github.com/spatialaudio/nbsphinx/assets/27275099/a06c7781-2568-4a86-9c5e-eb6112067c1b)

**Comment by mgeier** [comment]
> `nbconvert` also fails: should I report that to them?

Yes, or maybe even to IPython, see e.g. https://github.com/ipython/ipython/issues/9099 and https://github.com/ipython/ipython/pull/11137.

**Comment by jeertmans** [comment]
@mgeier done :-)
