### ISSUE TITLE
No module named ipython_genutils

### ISSUE THREAD

**Issue by john-science** [spatialaudio/nbsphinx#639]
My automated GitHub Actions builds that pull `nbsphinx` are now all failing with the error:

```bash
Extension error:
Could not import extension nbsphinx (exception: No module named 'ipython_genutils')
```

(We are using the most recent `nbsphinx==0.8.8`.) Is this a known issue? Do you have any advice?

Feel free to see a recent build [here](https://github.com/terrapower/armi/runs/5503784217?check_suite_focus=true).

**Comment by jaidisido** [comment]
I am facing a similar issue in my ReadTheDocs build

**Comment by john-science** [comment]
This bug may have been fixed in some downstream repository?

Evidence:

https://github.com/terrapower/armi/runs/5517430293?check_suite_focus=true

**Comment by john-science** [comment]
@jaidisido  Is this fixed in your ReadTheDocs build?

**Comment by mgeier** [comment]
See also #638, https://github.com/jupyter/nbconvert/issues/1725, https://github.com/jupyter/nbconvert/pull/1726.

The dependency was dropped in `nbclient` yesterday (https://github.com/jupyter/nbclient/releases/tag/v0.5.13), which broke `nbconvert`, which still depended on `ipython_genutils`.

This was quickly fixed in https://github.com/jupyter/nbconvert/pull/1727 and a new `nbconvert` release has been made: https://github.com/jupyter/nbconvert/releases/tag/6.4.3.

Now everything should be working again.

I guess in most cases it should work automatically, but if not, you can try to specify `nbconvert>=6.4.3`.

**Comment by john-science** [comment]
@mgeier Thanks so much for the information!
