### ISSUE TITLE
conda-forge recipe breaks

### ISSUE THREAD

**Issue by ericmjl** [spatialaudio/nbsphinx#66]
Hi nbsphinx team! I'd like to submit an nbsphinx recipe to conda-forge, so that I can build another package (i.e. PyMC3) in its totality, but I noticed that the build keeps breaking because of an import error. [[PR](https://github.com/conda-forge/staged-recipes/pull/1708)].

More specifically, conda-forge scripts require at least one test to be run, (please see [here](https://github.com/ericmjl/staged-recipes/blob/18c5eb4935dde4ef8c857326f765eff582f1347c/recipes/nbsphinx/meta.yaml#L30)), but I wasn't sure what would be the appropriate test to run after building and running. Would you be kind enough to advise please?

**Comment by mgeier** [comment]
I remember seeing the import error when doing `import nbsphinx` in an interactive session. When called by Sphinx, the module `sphinx.errors` seems to be imported already.

Can you please make a PR for the missing import?
I guess a `import sphinx.errors` should be sufficient, right?

The thing with the tests is a bit more involved, see #58 and #57.
It's quite laborious to make proper tests, because test cases would have to be Jupyter Notebooks (or their in-memory representation) and the resulting HTML/LaTeX files would have to be parsed to see if they have the expected contents (and if they even exist).
Probably Sphinx's own tests (https://github.com/sphinx-doc/sphinx/tree/master/tests) could be somehow re-used, but I don't really know if that's feasible.
Either way, I don't have the time nor the stamina to make proper tests.

If you want to do that, go ahead, I'd like to see a PR for that.

In the meantime, if importing isn't enough, I think it would be easiest to make some kind of dummy test for the conda recipe

```yaml
test:
  imports:
    - nbsphinx
  commands:
    - true  # [unix]
```

If you want, you can also try to build the nbsphinx docs as a test, the command `python setup.py build_sphinx` should do that, see [CONTRIBUTING.rst](../blob/master/CONTRIBUTING.rst).
I don't know if that'll work on the CI server, though ...

**Comment by mgeier** [comment]
@ericmjl I just made a new release (0.2.11) including the missing import.

**Comment by ericmjl** [comment]
@mgeier: thank you for the help! I'm sorry I didn't get to this earlier on, grad school got busy. I will try the new release and report back.

**Comment by mgeier** [comment]
@ericmjl Any news?

**Comment by ericmjl** [comment]
@mgeier: apologies again! Grad school... There's a recipe for 0.2.13 up on conda-forge. I think this can be closed!

**Comment by mgeier** [comment]
OK, thanks!
