### ISSUE TITLE
Spaces in notebook filename

### ISSUE THREAD

**Issue by senyai** [spatialaudio/nbsphinx#67]
Hi!

I have ipython notebook named "what is up.ipynb" containing one cell:

    from IPython.display import Image
    Image(filename='big.jpg')

The generated image will have name "what is up_0_0.jpeg", and sphinx will look for "whatisup_0_0.jpeg" which contains no spaces. So, the final document will have a broken image link.  "WARNING: image file not readable: _build/doctrees/nbsphinx/whatisup_0_0.jpeg" will be generated. I'm on Windows with python 2.7.10, having latest stable versions of sphinx and nbspinx. Manually removing spaces in image filenames is a quick way of fixing it.

**Comment by mgeier** [comment]
Thanks for the report!

Does #68 work for you?

**Comment by senyai** [comment]
Yes it does! I tried `User Guide - Basics.ipynb` and `User_Guide - Basics.ipynb` at the same time and the images are at right places.

**Comment by mgeier** [comment]
Thanks for testing this!

The image file name also contains the cell number and the number within the cell output (there may be several outputs per cell).

I guess if you have an image in the same cell in both of the files in your edge case, it will cease to work, right?

**Comment by senyai** [comment]
You guessed it right. I didn't understood the importance of cell numbers. Luckily, people don't name files that way, so nobody will blame you for this commit.

**Comment by mgeier** [comment]
Actually, I wanted to avoid this case, but I don't know how.

I tried to use %-encoding, like it's normally done in URLs, but this didn't work for some reason. Probably it's even a bug in Sphinx, because source names that contain `%AB` (where `A` and `B` are any hexadecimal characters) cannot be shown in the browser because Sphinx doesn't seem to escape those `%` signs.

If you know a way how to avoid this edge case, speak up!

Anyway, as you say, let's hope that people don't name their files in such a strange way ...

**Comment by mgeier** [comment]
I'm actually not sure if that's a bug or a feature of Sphinx, so I created an issue there: https://github.com/sphinx-doc/sphinx/issues/3097.
