### ISSUE TITLE
Links to other notebooks in markdown cells

### ISSUE THREAD

**Issue by SylvainCorlay** [spatialaudio/nbsphinx#70]
Is `nbsphinx` able to convert relative links to other notebooks in markdown cells to links to links html files?

It seems that the href is correct, but the `ipynb` extension needs to be converted to `html`.

cc @gnestor.

**Comment by gnestor** [comment]
Example: http://ipywidgets.readthedocs.io/en/latest/examples/Index.html?highlight=interactive%20widgets

**Comment by mgeier** [comment]
It *should* be possible, as shown here: http://nbsphinx.readthedocs.io/en/latest/markdown-cells.html#Links-to-Other-Notebooks

I don't know yet what's going wrong in your case, I'll investigate ...

I was wondering: Is there somewhere a link to `examples/Index.ipynb`? How would you even reach this page except per accident?
I only found an `examples.md`, which doesn't seem to be shown anywhere either ...

BTW, you could replace your [index.rst](https://raw.githubusercontent.com/ipython/ipywidgets/master/docs/source/index.rst) with a notebook, like it's shown in [the docs](http://nbsphinx.readthedocs.io/en/latest/subdir/toctree.html).

**Comment by gnestor** [comment]
I don't think there is a link to `examples/Index.ipynb`, but you can find it by searching for "interactive widgets." We are inquiring about this because a user opened an issue on ipywidgets: https://github.com/ipython/ipywidgets/issues/746. 

There are links at the top of a couple notebooks, such as http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html.

I took a look at the nbsphinx docs about linking to notebooks in markdown cells and it looks like we are doing this correctly: https://raw.githubusercontent.com/ipython/ipywidgets/master/docs/source/examples/Index.ipynb

**Comment by mgeier** [comment]
Yes, you are doing it correctly. This is a bug in `nbsphinx` which happens with file names containing spaces. I myself never use spaces in file names because it's kinda annoying to escape them on a terminal and there are many programs which have problems with them. In the near future, `nbsphinx` shouldn't be one of those programs anymore, because I hopefully fixed this in #71.

Can you please try if that works for you?

**Comment by SylvainCorlay** [comment]
@mgeier thanks for opening a PR so quickly!

**Comment by gnestor** [comment]
I tested by renaming `Widget List.ipynb` to `Widget-List.ipynb` and all links to it and that resolved it! I didn't test your PR but it looks good to me. Thanks @mgeier!

**Comment by mgeier** [comment]
Could one of you please actually test if #71 works for your case?

**Comment by SylvainCorlay** [comment]
Yes, I am cheering as @gnestor is doing all the hard work on this :)

**Comment by gnestor** [comment]
I tried testing by simply modifying [this line](https://github.com/ipython/ipywidgets/blob/master/docs/environment.yml#L16) in our environment.yml to `git+https://github.com/spatialaudio/nbsphinx.git#issue-70` and the links are still pointing to ipynb files. I'm not sure if I'm doing something incorrectly or if the PR is not actually URL-encoding the links.

**Comment by mgeier** [comment]
I've never used this, but according to [this stackoverflow answer](http://stackoverflow.com/a/32799944/500098) it should look somewhat like this:

```
dependencies:
   - pip:
     - "--editable=git+https://github.com/pythonforfacebook/facebook-sdk.git@8c0d34291aaafec00e02eaa71cc2a242790a0fcc#egg=facebook_sdk-master"
```

I normally install the development version of `nbsphinx` like described in [CONTRIBUTING.rst](../blob/master/CONTRIBUTING.rst).

**Comment by gnestor** [comment]
Ok, I was able to just clone the repo and switch to the issue-70 branch from within my conda environment. I rebuilt the docs and it works! Thanks @mgeier!

**Comment by gnestor** [comment]
Let us know when you push a new release and we will update our dependencies 👍

**Comment by SylvainCorlay** [comment]
👍

**Comment by mgeier** [comment]
There is a new `nbsphinx` release available now: https://pypi.python.org/pypi/nbsphinx/0.2.11

**Comment by gnestor** [comment]
Thanks @mgeier! We've bumped our dependency: https://github.com/ipython/ipywidgets/pull/912
