### ISSUE TITLE
nbsphinx gives WARNING: file not found: when valid path to a directory is provided in a link

### ISSUE THREAD

**Issue by michaelpacer** [spatialaudio/nbsphinx#74]
In the jupyter notebook documentation a link to a directory is specified in the line (if you wish, you can see [the link as part of our live documentation](http://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html)):

```markdown
See [Extending the Notebook](../../extending) for more documentation about writing nbextensions, server extensions, and bundler extensions.
```

This directory successfully resolves on html export: http://jupyter-notebook.readthedocs.io/en/latest/extending/

However, when building the html, it raises an error: 

    > WARNING: file not found: 'extending'

I looked into fixing this with a quick fix to indicate that it wasn't supposed to be a file (e.g., `[Extending the Notebook](../../extending/)`) but it doesn't seem to recognise that you can also link to directories in this manner. 

I think this arises because of the code at:  https://github.com/spatialaudio/nbsphinx/blob/master/nbsphinx.py#L911

I'm not sure what your preferred solution to this would be. It could either look for a trailing `/` and then treat it as a directory call (meaning the current code can mostly be untouched) or it should fall back when a file is not found and test whether a directory with the same name is present in the same location.

**Comment by mgeier** [comment]
I don't think this is a feature of Sphinx.
I guess this is only working by accident for HTML output on RTD, because it happens to serve `index.html` by default.
In Sphinx, AFAIK there is no concept of a "default" file in a directory, you'll have to specify a link to an actual Sphinx source file for this to work.
Even if this does seem to work for HTML output, it definitely breaks in LaTeX output.
Therefore, I think the warning is appropriate.

Also, this wouldn't work in The Notebook itself, would it?

BTW, you could replace https://github.com/jupyter/notebook/blob/master/docs/source/extending/index.rst by a Jupyter notebook (using the [nbsphinx-toctree](http://nbsphinx.readthedocs.io/en/latest/subdir/toctree.html) metadata), then it is easier to use within The Notebook.

**Comment by michaelpacer** [comment]
In the notebook itself, it opens a view on the directory in the a new tab
of the notebook dashboard.

I think that's fair regarding the point in LaTeX output.

You're right that at the least it should be a direct link to the index file.

Re: transforming it into a notebook & using nbsphinx-toctree metadata is an
interesting approach, I'll look into that.
