### ISSUE TITLE
notebook crossreferences that work in one output format(html) but break in another (LaTeX)

### ISSUE THREAD

**Issue by mpacer** [spatialaudio/nbsphinx#82]
Cross references written in terms of html crossrefs are not always interpreted appropriately by nbsphinx in LaTeX export. 

for example in https://github.com/jupyter/nbconvert/blob/master/docs/source/architecture.rst we have 

    see-also::

        `Custom Preprocessors <nbconvert_library.html#Custom-Preprocessors>`_

which is correctly handled for html export but in the LaTeX export this is converted to: 

    \sphinxstrong{See also:}
    {\hyperref[external_exporters:external\string-exporters]{\sphinxcrossref{\DUrole{std,std-ref}{Writing a custom Exporter}}}}

When it should be 

    \sphinxstrong{See also:}
    \hyperref[nbconvert_library:Custom-Preprocessors]{\sphinxcrossref{\DUrole{std,std-ref}{Custom-Preprocessors}}}

What's weird is the wrong one is taking content from two different places, one is a chapter heading that has the content "Customizing exporters" the other is a heading with the content "Writing a custom \texttt{Exporter}". 

As a hint — the :doc: directive seems to be successfully linking inside `.ipynb` files (i.e., :doc:`nbconvert_library` seems to successfully convert to `{\hyperref[nbconvert_library::doc]{\sphinxcrossref{\DUrole{doc}{Using nbconvert as a library}}}}`).

**Comment by mgeier** [comment]
You are supposed to link to Sphinx source files, *not* to the generated HTML pages (which of course don't exist when building LaTeX). The links may work in HTML output, but that's by accident.

It should work by default if you use ``:doc:`nbconvert_library` ``, because Sphinx doesn't need the file extension here (and auto-completes `.ipynb`, not `.html`).

Using `nbsphinx`, you can also use `:ref:` references, as described in [the docs](http://nbsphinx.readthedocs.io/en/latest/a-normal-rst-file.html#links-to-notebooks). There are some limitations though, but they are also in the docs. Those are not simply path names, those are actually section labels that are specially created by `nbsphinx.CreateSectionLabels`.

I've never tried "normal" reST-style links, but I guess they are not supposed to link to source files, right?
Those are for "web links", see http://www.sphinx-doc.org/en/latest/rest.html#hyperlinks.

Does all that make sense?

**Comment by mgeier** [comment]
@michaelpacer Any more comments on this?
I think there is nothing to do for me, or is there?
