### ISSUE TITLE
Is there an in-place mechanism for converting a single notebook for nbsphinx dev purposes?

### ISSUE THREAD

**Issue by mpacer** [spatialaudio/nbsphinx#83]
Hi, right now it seems like the only way to see the output of nbsphinx on a notebook is indirectly through sphinx. Is there an API or some straightforward workflow for use in the style of nbconvert on a single notebook to see what the comparable html/rst/LaTeX output would be? 

One example of a case that seems like too much of a hassle to fight with indirectly is debugging https://github.com/spatialaudio/nbsphinx/issues/82. If there is a more iterative way of interacting with the nbsphinx codebase and to try out these things, then I think I'd be able to contribute here more easily. 

If not, no worries, I just wanted to check.

**Comment by mgeier** [comment]
AFAIK, there is no way to run Sphinx for a single source file.
It also doesn't really make sense, since none of the links to or definitions from other files would work.
I don't think it would help in your debugging of #82, since the links wouldn't work anyway.

You can also try other things:

* create a brand-new Sphinx project with only a simple `index.rst` and only one other source file, i.e. the notebook you want to debug.

* use `nbsphinx.Exporter.from_filename()` to get a reST string from your notebook. Note however, that this will disappear with #36.

The links still wouldn't work either way.

For `nbsphinx` development, I normally use the `nbsphinx` docs. Most of the supported features are also used in the docs, e.g. the stuff about links from `.rst` files to `.ipynb` file is [there](http://nbsphinx.readthedocs.io/en/latest/a-normal-rst-file.html#links-to-notebooks).
If something is missing in the docs, please let me know.

**Comment by mgeier** [comment]
@mpacer Does that answer your question?

Do you have any more comments?
