### ISSUE TITLE
clear notebooks after executing

### ISSUE THREAD

**Issue by arsenovic** [spatialaudio/nbsphinx#92]
if notebooks are kept track of using git, it seems that you would want to clear all outputs after the sphinx docs have been built, otherwise the git repo will grow and grow with any change. especially with plots.

**Comment by arsenovic** [comment]
https://github.com/rbeagrie/ipynb_stripout

maybe we could sub-module or just include this feature?

**Comment by mgeier** [comment]
`nbsphinx` doesn't add any outputs, so IMHO it shouldn't remove them either.
On the contrary, `nbsphinx` should never modify any source files in any way. Given the architecture of Sphinx, this wouldn't really make sense anyway. Source files are not supposed to be changed.

I'd recommend to everybody to not include the outputs in the Git repo, but I think it's not the task of `nbsphinx` to do anything about it. Since the beginning, `nbsphinx` supported auto-executing "empty" notebooks, but making them empty was never part of the plan.

If you want, we can include recommendations about this in the documentation and we can link to tools that help users with the task of removing outputs.
Feel free to make a PR for that!

**Comment by arsenovic** [comment]
ok thanks for explaining, i did not understand how it worked. 

so if i understand you; if the notebook output is cleared, and nbsphinx is set to execute the notebook, then it does not change the files (ie they remain cleared)

**Comment by mgeier** [comment]
Notebook execution is explained in the docs: http://nbsphinx.readthedocs.io/en/0.2.12/executing-notebooks.html. It's also mentioned in the very first paragraph of the documentation.

If anything about the documentation can be improved, please make a PR or an issue.

And yes, by default an empty notebook is executed. But users can change this behavior, see http://nbsphinx.readthedocs.io/en/0.2.12/never-execute.html.

And yes, the source files (i.e. the `*.ipynb` files) are not changed. Ever.

If `nbsphinx` executes a notebook, it does that with an in-memory copy of the notebook (using the `nbformat` and `nbconvert` Python modules). I think the source directory can even be read-only, it should still work.

You can also have a look at the source code itself (`nbsphinx.py`), it shouldn't be too hard to understand. Just search for a function called `from_notebook_node()`. And before that, a function called `parse()` is called by Sphinx, which provides the notebook contents as a string. We don't even get the source file itself, only a copy of its contents!

**Comment by arsenovic** [comment]
ok thanks
